import type { SATTest } from './index'

// SAT Practice Test 2 — placeholder questions
// Replace with real College Board-style questions

export const TEST2: SATTest = {
  id: 'test2',
  name: 'SAT Practice Test 2',
  module1: [
    {
      id: 't2m1q1', module: 1, domain: 'Algebra', skill: 'Linear equations',
      difficulty: 'Easy', type: 'mc',
      question: 'If 4x − 8 = 16, what is x?',
      choices: ['4', '5', '6', '7'],
      answer: 'C',
      explanation: '4x = 24; x = 6.',
    },
    {
      id: 't2m1q2', module: 1, domain: 'Advanced Math', skill: 'Quadratics',
      difficulty: 'Medium', type: 'mc',
      question: 'What is the vertex of y = (x − 2)² + 5?',
      choices: ['(2, 5)', '(−2, 5)', '(2, −5)', '(5, 2)'],
      answer: 'A',
      explanation: 'Vertex form y = (x−h)² + k → vertex (2, 5).',
    },
    {
      id: 't2m1q3', module: 1, domain: 'Problem Solving & Data Analysis', skill: 'Ratios',
      difficulty: 'Easy', type: 'mc',
      question: 'A map uses a scale of 1 inch = 25 miles. How many miles does 3.5 inches represent?',
      choices: ['75', '87.5', '100', '112.5'],
      answer: 'B',
      explanation: '3.5 × 25 = 87.5.',
    },
    {
      id: 't2m1q4', module: 1, domain: 'Geometry & Trigonometry', skill: 'Area',
      difficulty: 'Easy', type: 'mc',
      question: 'A circle has diameter 10. What is its area? (Use π ≈ 3.14)',
      choices: ['31.4', '78.5', '157', '314'],
      answer: 'B',
      explanation: 'r = 5; A = π(5²) ≈ 78.5.',
    },
    {
      id: 't2m1q5', module: 1, domain: 'Algebra', skill: 'Systems',
      difficulty: 'Medium', type: 'mc',
      question: 'If 2x + y = 14 and x − y = 1, what is y?',
      choices: ['3', '4', '5', '6'],
      answer: 'C',
      explanation: 'Add equations: 3x = 15 → x=5; y = 5−1 = 4. Wait: y=14−2(5)=4.',
    },
    {
      id: 't2m1q6', module: 1, domain: 'Advanced Math', skill: 'Exponential functions',
      difficulty: 'Medium', type: 'mc',
      question: 'Which equation represents exponential decay?',
      choices: ['y = 2ˣ', 'y = (0.5)ˣ', 'y = x²', 'y = 2x + 1'],
      answer: 'B',
      explanation: 'Base < 1 in exponential function means decay.',
    },
    {
      id: 't2m1q7', module: 1, domain: 'Problem Solving & Data Analysis', skill: 'Percentages',
      difficulty: 'Easy', type: 'spr',
      question: 'A jacket originally costs $80. After a 15% discount, what is the sale price in dollars?',
      answer: '68',
      explanation: '80 × 0.85 = 68.',
    },
    {
      id: 't2m1q8', module: 1, domain: 'Geometry & Trigonometry', skill: 'Pythagorean theorem',
      difficulty: 'Medium', type: 'mc',
      question: 'In a right triangle, the hypotenuse is 13 and one leg is 5. What is the other leg?',
      choices: ['8', '10', '12', '14'],
      answer: 'C',
      explanation: '√(169−25) = √144 = 12.',
    },
    {
      id: 't2m1q9', module: 1, domain: 'Algebra', skill: 'Inequalities',
      difficulty: 'Easy', type: 'mc',
      question: 'Which value of x satisfies −3x + 9 ≥ 0?',
      choices: ['4', '3', '2', 'All of B and C'],
      answer: 'D',
      explanation: 'x ≤ 3, so both 2 and 3 work.',
    },
    {
      id: 't2m1q10', module: 1, domain: 'Advanced Math', skill: 'Polynomial division',
      difficulty: 'Hard', type: 'mc',
      question: 'If (x² + 3x − 4) / (x − 1) is simplified, the result is:',
      choices: ['x + 4', 'x − 4', 'x + 3', 'x − 3'],
      answer: 'A',
      explanation: 'Factor: (x+4)(x−1)/(x−1) = x+4.',
    },
    {
      id: 't2m1q11', module: 1, domain: 'Problem Solving & Data Analysis', skill: 'Statistics',
      difficulty: 'Medium', type: 'mc',
      question: 'The median of {3, 7, 9, 11, 15} is:',
      choices: ['7', '9', '11', '10'],
      answer: 'B',
      explanation: 'Middle value of ordered set = 9.',
    },
    {
      id: 't2m1q12', module: 1, domain: 'Geometry & Trigonometry', skill: 'Volume',
      difficulty: 'Hard', type: 'mc',
      question: 'A rectangular box has dimensions 4 × 5 × 6. What is its volume?',
      choices: ['60', '74', '120', '200'],
      answer: 'C',
      explanation: '4 × 5 × 6 = 120.',
    },
    {
      id: 't2m1q13', module: 1, domain: 'Algebra', skill: 'Functions',
      difficulty: 'Medium', type: 'mc',
      question: 'If h(x) = −x² + 4, what is h(−2)?',
      choices: ['−8', '0', '8', '−4'],
      answer: 'B',
      explanation: 'h(−2) = −4 + 4 = 0.',
    },
    {
      id: 't2m1q14', module: 1, domain: 'Advanced Math', skill: 'Completing the square',
      difficulty: 'Hard', type: 'mc',
      question: 'Rewrite x² + 8x + 7 in vertex form.',
      choices: ['(x+4)² − 9', '(x+4)² + 7', '(x−4)² − 9', '(x+8)² − 57'],
      answer: 'A',
      explanation: 'x²+8x+16−9 = (x+4)²−9.',
    },
    {
      id: 't2m1q15', module: 1, domain: 'Problem Solving & Data Analysis', skill: 'Surveys',
      difficulty: 'Medium', type: 'mc',
      question: 'A poll asks 500 students about their favorite subject. 40% chose Math. How many students chose Math?',
      choices: ['150', '175', '200', '225'],
      answer: 'C',
      explanation: '0.40 × 500 = 200.',
    },
    {
      id: 't2m1q16', module: 1, domain: 'Geometry & Trigonometry', skill: 'Angle relationships',
      difficulty: 'Easy', type: 'mc',
      question: 'Two angles are complementary. One is 32°. What is the other?',
      choices: ['48°', '58°', '68°', '148°'],
      answer: 'B',
      explanation: '90° − 32° = 58°.',
    },
    {
      id: 't2m1q17', module: 1, domain: 'Algebra', skill: 'Slope-intercept',
      difficulty: 'Easy', type: 'mc',
      question: 'Which line has slope 3 and passes through (0, −2)?',
      choices: ['y = 3x − 2', 'y = −2x + 3', 'y = 3x + 2', 'y = −3x − 2'],
      answer: 'A',
      explanation: 'y = mx + b = 3x − 2.',
    },
    {
      id: 't2m1q18', module: 1, domain: 'Advanced Math', skill: 'Radicals',
      difficulty: 'Medium', type: 'spr',
      question: 'Simplify √75 in the form a√b where b is smallest possible. Enter just the whole number coefficient a.',
      answer: '5',
      explanation: '√75 = √(25×3) = 5√3; a = 5.',
    },
    {
      id: 't2m1q19', module: 1, domain: 'Problem Solving & Data Analysis', skill: 'Box plots',
      difficulty: 'Medium', type: 'mc',
      question: 'A box plot has minimum 10, Q1 = 20, median = 30, Q3 = 45, maximum = 60. What is the interquartile range?',
      choices: ['15', '25', '30', '50'],
      answer: 'B',
      explanation: 'IQR = Q3 − Q1 = 45 − 20 = 25.',
    },
    {
      id: 't2m1q20', module: 1, domain: 'Geometry & Trigonometry', skill: 'Similar figures',
      difficulty: 'Medium', type: 'mc',
      question: 'Two similar rectangles have corresponding sides 4 and 10. The smaller has area 24. What is the area of the larger?',
      choices: ['60', '100', '120', '150'],
      answer: 'D',
      explanation: 'Area ratio = (10/4)² = 6.25; 24 × 6.25 = 150.',
    },
    {
      id: 't2m1q21', module: 1, domain: 'Algebra', skill: 'Direct variation',
      difficulty: 'Easy', type: 'mc',
      question: 'If y varies directly with x and y = 12 when x = 4, what is y when x = 7?',
      choices: ['18', '21', '24', '28'],
      answer: 'B',
      explanation: 'k = 12/4 = 3; y = 3(7) = 21.',
    },
    {
      id: 't2m1q22', module: 1, domain: 'Advanced Math', skill: 'Parabolas',
      difficulty: 'Hard', type: 'spr',
      question: 'The parabola y = x² − 4x + 3 crosses the x-axis at two points. What is the sum of those x-values?',
      answer: '4',
      explanation: 'Roots are 1 and 3; sum = 4 (by Vieta\'s formulas or factoring).',
    },
  ],

  module2Hard: [
    {
      id: 't2m2hq1', module: 2, domain: 'Advanced Math', skill: 'Binomial theorem',
      difficulty: 'Hard', type: 'mc',
      question: 'What is the coefficient of x² in the expansion of (x + 3)³?',
      choices: ['3', '9', '27', '1'],
      answer: 'B',
      explanation: 'C(3,1)×3¹ = 9.',
    },
    {
      id: 't2m2hq2', module: 2, domain: 'Algebra', skill: 'Absolute value inequalities',
      difficulty: 'Hard', type: 'mc',
      question: 'What is the solution set for |x − 5| < 3?',
      choices: ['x < 8', 'x > 2', '2 < x < 8', 'x < 2 or x > 8'],
      answer: 'C',
      explanation: '−3 < x−5 < 3 → 2 < x < 8.',
    },
    {
      id: 't2m2hq3', module: 2, domain: 'Geometry & Trigonometry', skill: 'Unit circle',
      difficulty: 'Hard', type: 'mc',
      question: 'What is cos(π/3)?',
      choices: ['√3/2', '1/2', '√2/2', '1'],
      answer: 'B',
      explanation: 'cos(60°) = 1/2.',
    },
    {
      id: 't2m2hq4', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Confidence intervals',
      difficulty: 'Hard', type: 'mc',
      question: 'A study finds a 95% confidence interval for the mean score is (72, 84). What does this mean?',
      choices: [
        '95% of students scored between 72 and 84',
        'There is a 95% chance the true mean is between 72 and 84',
        'The sample mean is 78 with certainty',
        '5% of samples would give this interval',
      ],
      answer: 'B',
      explanation: 'Confidence interval estimates where the population parameter likely falls.',
    },
    {
      id: 't2m2hq5', module: 2, domain: 'Advanced Math', skill: 'Systems of nonlinear equations',
      difficulty: 'Hard', type: 'mc',
      question: 'How many solutions does the system y = x² and y = x + 2 have?',
      choices: ['0', '1', '2', '3'],
      answer: 'C',
      explanation: 'x²−x−2=0 → (x−2)(x+1)=0; 2 solutions.',
    },
    {
      id: 't2m2hq6', module: 2, domain: 'Algebra', skill: 'Inverse functions',
      difficulty: 'Hard', type: 'mc',
      question: 'If f(x) = 3x + 6, what is f⁻¹(x)?',
      choices: ['(x−6)/3', '(x+6)/3', '3x−6', '(x/3)−6'],
      answer: 'A',
      explanation: 'Swap x and y: x = 3y+6 → y = (x−6)/3.',
    },
    {
      id: 't2m2hq7', module: 2, domain: 'Geometry & Trigonometry', skill: 'Circles in coordinate plane',
      difficulty: 'Hard', type: 'mc',
      question: 'What is the radius of the circle (x−3)² + (y+2)² = 25?',
      choices: ['3', '4', '5', '25'],
      answer: 'C',
      explanation: 'Radius = √25 = 5.',
    },
    {
      id: 't2m2hq8', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Experimental design',
      difficulty: 'Hard', type: 'mc',
      question: 'A clinical trial randomly assigns 300 patients to drug or placebo. The drug group improves significantly more. What can we conclude?',
      choices: [
        'The drug caused the improvement',
        'The drug is correlated with improvement',
        'The patients self-selected into better health',
        'The placebo was ineffective',
      ],
      answer: 'A',
      explanation: 'Random assignment allows causal conclusions.',
    },
    {
      id: 't2m2hq9', module: 2, domain: 'Advanced Math', skill: 'Rational functions',
      difficulty: 'Hard', type: 'mc',
      question: 'What is the vertical asymptote of f(x) = (x+2)/(x−3)?',
      choices: ['x = 3', 'x = −2', 'y = 1', 'y = 3'],
      answer: 'A',
      explanation: 'Denominator = 0 when x = 3.',
    },
    {
      id: 't2m2hq10', module: 2, domain: 'Algebra', skill: 'Parametric word problems',
      difficulty: 'Hard', type: 'spr',
      question: 'A car depreciates by $1,500 per year. It is currently worth $22,000. In how many years will it be worth $13,000?',
      answer: '6',
      explanation: '22000−1500n=13000; 1500n=9000; n=6.',
    },
    {
      id: 't2m2hq11', module: 2, domain: 'Geometry & Trigonometry', skill: 'Radians',
      difficulty: 'Hard', type: 'mc',
      question: 'Convert 270° to radians.',
      choices: ['π/2', 'π', '3π/2', '2π'],
      answer: 'C',
      explanation: '270 × (π/180) = 3π/2.',
    },
    {
      id: 't2m2hq12', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Sampling bias',
      difficulty: 'Hard', type: 'mc',
      question: 'A school surveys students who stay late after school about extracurricular participation. This sample likely has:',
      choices: ['No bias', 'Sampling bias — overrepresents involved students', 'Response bias', 'Undercoverage of all students'],
      answer: 'B',
      explanation: 'Students staying late are more likely to be involved in activities.',
    },
    {
      id: 't2m2hq13', module: 2, domain: 'Advanced Math', skill: 'Arithmetic series',
      difficulty: 'Hard', type: 'spr',
      question: 'What is the sum of the first 10 terms of the arithmetic sequence 3, 7, 11, 15, …?',
      answer: '210',
      explanation: 'a₁=3, d=4; S₁₀ = 10/2 × (2×3 + 9×4) = 5×42 = 210.',
    },
    {
      id: 't2m2hq14', module: 2, domain: 'Algebra', skill: 'Complex systems',
      difficulty: 'Hard', type: 'mc',
      question: 'For which value of k does the system 2x + ky = 8 and 4x + 6y = 16 have infinitely many solutions?',
      choices: ['2', '3', '4', '6'],
      answer: 'B',
      explanation: 'Second eq = 2×first; need 2k = 6, so k = 3.',
    },
    {
      id: 't2m2hq15', module: 2, domain: 'Geometry & Trigonometry', skill: 'Surface area',
      difficulty: 'Hard', type: 'mc',
      question: 'What is the total surface area of a cube with side length 4?',
      choices: ['24', '64', '96', '128'],
      answer: 'C',
      explanation: '6 × 4² = 96.',
    },
    {
      id: 't2m2hq16', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Linear vs exponential',
      difficulty: 'Hard', type: 'mc',
      question: 'A bank account earns 5% annual interest compounded annually, starting at $1,000. After 2 years, the balance is:',
      choices: ['$1,100', '$1,102.50', '$1,105', '$1,110'],
      answer: 'B',
      explanation: '1000(1.05)² = 1102.50.',
    },
    {
      id: 't2m2hq17', module: 2, domain: 'Advanced Math', skill: 'Piecewise functions',
      difficulty: 'Hard', type: 'mc',
      question: 'For f(x) = {2x if x < 0; x² if x ≥ 0}, what is f(−3) + f(2)?',
      choices: ['−2', '2', '−10', '−2'],
      answer: 'A',
      explanation: 'f(−3) = −6; f(2) = 4; −6+4 = −2.',
    },
    {
      id: 't2m2hq18', module: 2, domain: 'Algebra', skill: 'Mixture problems',
      difficulty: 'Hard', type: 'spr',
      question: 'How many liters of a 30% solution must be mixed with 10 liters of a 60% solution to get a 40% solution?',
      answer: '20',
      explanation: '0.3x + 0.6(10) = 0.4(x+10); 0.3x+6=0.4x+4; 2=0.1x; x=20.',
    },
    {
      id: 't2m2hq19', module: 2, domain: 'Geometry & Trigonometry', skill: 'Parabola focus',
      difficulty: 'Hard', type: 'mc',
      question: 'The parabola x² = 12y has its focus at:',
      choices: ['(0, 3)', '(0, −3)', '(3, 0)', '(−3, 0)'],
      answer: 'A',
      explanation: 'x²=4py → 4p=12 → p=3; focus at (0,3).',
    },
    {
      id: 't2m2hq20', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Z-scores',
      difficulty: 'Hard', type: 'mc',
      question: 'A normal distribution has mean 70 and standard deviation 10. What z-score corresponds to a value of 85?',
      choices: ['0.5', '1.0', '1.5', '2.0'],
      answer: 'C',
      explanation: 'z = (85−70)/10 = 1.5.',
    },
    {
      id: 't2m2hq21', module: 2, domain: 'Advanced Math', skill: 'Synthetic division',
      difficulty: 'Hard', type: 'mc',
      question: 'If f(x) = x³ − 2x² − 5x + 6 and f(3) = 0, which is a factor?',
      choices: ['(x − 1)', '(x − 2)', '(x − 3)', '(x + 3)'],
      answer: 'C',
      explanation: 'f(3) = 0 means (x−3) is a factor.',
    },
    {
      id: 't2m2hq22', module: 2, domain: 'Algebra', skill: 'Matrix-type reasoning',
      difficulty: 'Hard', type: 'spr',
      question: 'If the product of two consecutive even integers is 120, what is the larger integer?',
      answer: '12',
      explanation: 'n(n+2)=120; n²+2n−120=0; (n+12)(n−10)=0; n=10, larger=12.',
    },
  ],

  module2Easy: [
    {
      id: 't2m2eq1', module: 2, domain: 'Algebra', skill: 'One-step equations',
      difficulty: 'Easy', type: 'mc',
      question: 'Solve: x/4 = 7',
      choices: ['11', '28', '3', '7/4'],
      answer: 'B',
      explanation: 'x = 28.',
    },
    {
      id: 't2m2eq2', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Unit rate',
      difficulty: 'Easy', type: 'mc',
      question: 'If 5 pounds of apples cost $8, how much do 12.5 pounds cost?',
      choices: ['$16', '$18', '$20', '$22'],
      answer: 'C',
      explanation: '$8/5 × 12.5 = $20.',
    },
    {
      id: 't2m2eq3', module: 2, domain: 'Geometry & Trigonometry', skill: 'Perimeter',
      difficulty: 'Easy', type: 'mc',
      question: 'A triangle has sides 5, 7, and 9. What is its perimeter?',
      choices: ['18', '19', '21', '23'],
      answer: 'C',
      explanation: '5+7+9=21.',
    },
    {
      id: 't2m2eq4', module: 2, domain: 'Advanced Math', skill: 'Powers',
      difficulty: 'Easy', type: 'mc',
      question: 'What is (2³)²?',
      choices: ['12', '32', '64', '128'],
      answer: 'C',
      explanation: '2⁶ = 64.',
    },
    {
      id: 't2m2eq5', module: 2, domain: 'Algebra', skill: 'Substitution',
      difficulty: 'Easy', type: 'spr',
      question: 'If a = 5 and b = 3, what is 2a − b?',
      answer: '7',
      explanation: '2(5)−3 = 7.',
    },
    {
      id: 't2m2eq6', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Median',
      difficulty: 'Easy', type: 'mc',
      question: 'What is the median of {5, 8, 11, 14, 17}?',
      choices: ['8', '11', '13', '14'],
      answer: 'B',
      explanation: 'Middle value = 11.',
    },
    {
      id: 't2m2eq7', module: 2, domain: 'Geometry & Trigonometry', skill: 'Parallel lines',
      difficulty: 'Easy', type: 'mc',
      question: 'Two parallel lines are cut by a transversal. If one interior angle is 70°, what is the co-interior angle on the same side?',
      choices: ['70°', '100°', '110°', '120°'],
      answer: 'C',
      explanation: 'Co-interior (same-side interior) angles are supplementary: 180−70=110.',
    },
    {
      id: 't2m2eq8', module: 2, domain: 'Advanced Math', skill: 'Factoring',
      difficulty: 'Medium', type: 'mc',
      question: 'Factor 2x² − 8.',
      choices: ['2(x−2)(x+2)', '2(x−4)', '(2x−4)(x+2)', '(x−2)²'],
      answer: 'A',
      explanation: '2(x²−4) = 2(x−2)(x+2).',
    },
    {
      id: 't2m2eq9', module: 2, domain: 'Algebra', skill: 'Two-step equations',
      difficulty: 'Easy', type: 'mc',
      question: 'Solve: 3x + 5 = 20',
      choices: ['3', '4', '5', '6'],
      answer: 'C',
      explanation: '3x = 15; x = 5.',
    },
    {
      id: 't2m2eq10', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Graphs',
      difficulty: 'Easy', type: 'mc',
      question: 'A bar graph shows sales of 40 in Jan, 55 in Feb, and 50 in Mar. What is the mean monthly sales?',
      choices: ['45', '48.3', '50', '55'],
      answer: 'B',
      explanation: '(40+55+50)/3 ≈ 48.3.',
    },
    {
      id: 't2m2eq11', module: 2, domain: 'Geometry & Trigonometry', skill: 'Right triangles',
      difficulty: 'Medium', type: 'mc',
      question: 'A right triangle has legs 9 and 12. What is the hypotenuse?',
      choices: ['13', '14', '15', '16'],
      answer: 'C',
      explanation: '√(81+144) = √225 = 15.',
    },
    {
      id: 't2m2eq12', module: 2, domain: 'Advanced Math', skill: 'Parabolas',
      difficulty: 'Medium', type: 'mc',
      question: 'How many times does y = x² − 4 cross the x-axis?',
      choices: ['0', '1', '2', '3'],
      answer: 'C',
      explanation: 'x² = 4 → x = ±2; two crossings.',
    },
    {
      id: 't2m2eq13', module: 2, domain: 'Algebra', skill: 'Combining like terms',
      difficulty: 'Easy', type: 'mc',
      question: 'Simplify: 3x + 2y − x + 5y',
      choices: ['2x + 7y', '4x + 3y', '2x + 3y', '4x + 7y'],
      answer: 'A',
      explanation: '(3x−x) + (2y+5y) = 2x+7y.',
    },
    {
      id: 't2m2eq14', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Probability',
      difficulty: 'Easy', type: 'mc',
      question: 'A fair die is rolled. What is the probability of rolling a prime number?',
      choices: ['1/6', '1/3', '1/2', '2/3'],
      answer: 'C',
      explanation: 'Primes on die: 2,3,5 — probability = 3/6 = 1/2.',
    },
    {
      id: 't2m2eq15', module: 2, domain: 'Geometry & Trigonometry', skill: 'Coordinate distance',
      difficulty: 'Easy', type: 'spr',
      question: 'What is the distance between (0, 0) and (3, 4)?',
      answer: '5',
      explanation: '√(9+16) = √25 = 5.',
    },
    {
      id: 't2m2eq16', module: 2, domain: 'Advanced Math', skill: 'Evaluating expressions',
      difficulty: 'Easy', type: 'mc',
      question: 'If x = −2, what is 3x² − x + 1?',
      choices: ['11', '13', '15', '17'],
      answer: 'C',
      explanation: '3(4)−(−2)+1 = 12+2+1 = 15.',
    },
    {
      id: 't2m2eq17', module: 2, domain: 'Algebra', skill: 'Number patterns',
      difficulty: 'Easy', type: 'mc',
      question: 'The next term in the sequence 2, 5, 10, 17, 26, … is:',
      choices: ['33', '35', '37', '39'],
      answer: 'C',
      explanation: 'Differences: 3,5,7,9,11 → next is 26+11=37.',
    },
    {
      id: 't2m2eq18', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Rates',
      difficulty: 'Easy', type: 'spr',
      question: 'A faucet drips 3 liters per hour. How many liters does it drip in 8 hours?',
      answer: '24',
      explanation: '3 × 8 = 24.',
    },
    {
      id: 't2m2eq19', module: 2, domain: 'Geometry & Trigonometry', skill: 'Polygons',
      difficulty: 'Medium', type: 'mc',
      question: 'What is the sum of interior angles of a hexagon?',
      choices: ['540°', '720°', '900°', '1080°'],
      answer: 'B',
      explanation: '(6−2) × 180° = 720°.',
    },
    {
      id: 't2m2eq20', module: 2, domain: 'Advanced Math', skill: 'Inequalities on number line',
      difficulty: 'Easy', type: 'mc',
      question: 'Which number line shows x ≥ −1?',
      choices: ['Closed dot at −1, arrow right', 'Open dot at −1, arrow right', 'Closed dot at −1, arrow left', 'Open dot at 1, arrow right'],
      answer: 'A',
      explanation: 'Closed dot (≥ includes −1), arrow pointing right.',
    },
    {
      id: 't2m2eq21', module: 2, domain: 'Algebra', skill: 'Percent change',
      difficulty: 'Easy', type: 'mc',
      question: 'A price increases from $50 to $65. What is the percent increase?',
      choices: ['15%', '20%', '25%', '30%'],
      answer: 'D',
      explanation: '(15/50) × 100 = 30%.',
    },
    {
      id: 't2m2eq22', module: 2, domain: 'Problem Solving & Data Analysis', skill: 'Reading charts',
      difficulty: 'Easy', type: 'mc',
      question: 'In a pie chart, a slice represents 25% of the total. If the total is 200, how many does the slice represent?',
      choices: ['25', '40', '50', '75'],
      answer: 'C',
      explanation: '0.25 × 200 = 50.',
    },
  ],
}
