export interface SeedQuestion {
  subject: 'ap_precalc' | 'sat_math'
  topic: string
  subtopic: string
  question_text: string
  answer_text: string
  choices: string[]
  difficulty: number
  explanation: string
}

export const seedQuestions: SeedQuestion[] = [
  // ── AP PRECALCULUS: FUNCTIONS (8) ──────────────────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Evaluating Functions',
    question_text: 'If f(x) = 3x² − 2x + 1, what is f(−2)?',
    answer_text: 'A',
    choices: ['A) 17', 'B) 9', 'C) 21', 'D) 13'],
    difficulty: 1,
    explanation: 'f(−2) = 3(4) − 2(−2) + 1 = 12 + 4 + 1 = 17',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Domain and Range',
    question_text: 'Which of the following is the domain of f(x) = √(x − 3)?',
    answer_text: 'A',
    choices: ['A) x ≥ 3', 'B) x > 3', 'C) x ≤ 3', 'D) All real numbers'],
    difficulty: 1,
    explanation: 'The radicand must be ≥ 0, so x − 3 ≥ 0 → x ≥ 3',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Composition of Functions',
    question_text: 'If f(x) = 2x + 1 and g(x) = x², what is f(g(3))?',
    answer_text: 'A',
    choices: ['A) 19', 'B) 49', 'C) 37', 'D) 10'],
    difficulty: 2,
    explanation: 'g(3) = 9, f(9) = 2(9) + 1 = 19',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Inverse Functions',
    question_text: 'What is the inverse of f(x) = (x + 4)/3?',
    answer_text: 'A',
    choices: ['A) f⁻¹(x) = 3x − 4', 'B) f⁻¹(x) = 3x + 4', 'C) f⁻¹(x) = (x − 4)/3', 'D) f⁻¹(x) = x/3 − 4'],
    difficulty: 2,
    explanation: 'Swap x and y: x = (y+4)/3 → 3x = y+4 → y = 3x−4',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Even and Odd Functions',
    question_text: 'Which function is even?',
    answer_text: 'A',
    choices: ['A) f(x) = x⁴ − 3x²', 'B) f(x) = x³ + x', 'C) f(x) = x² − 2x', 'D) f(x) = |x| + x'],
    difficulty: 2,
    explanation: 'f(−x) = (−x)⁴ − 3(−x)² = x⁴ − 3x² = f(x), so it is even',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Domain and Range',
    question_text: 'If f(x) = x/(x−2), what value is NOT in the domain?',
    answer_text: 'A',
    choices: ['A) 2', 'B) 0', 'C) −2', 'D) 1'],
    difficulty: 1,
    explanation: 'The denominator equals zero when x = 2, so x = 2 is excluded',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Domain and Range',
    question_text: 'For f(x) = √(9 − x²), what is the range?',
    answer_text: 'A',
    choices: ['A) 0 ≤ y ≤ 3', 'B) −3 ≤ y ≤ 3', 'C) y ≥ 0', 'D) y ≤ 3'],
    difficulty: 3,
    explanation: 'The function defines the upper half of a circle of radius 3; range is [0, 3]',
  },
  {
    subject: 'ap_precalc',
    topic: 'Functions',
    subtopic: 'Composition of Functions',
    question_text: 'If h(x) = (f ∘ g)(x) where f(x) = x + 2 and g(x) = 3x, then h(4) = ?',
    answer_text: 'A',
    choices: ['A) 14', 'B) 18', 'C) 12', 'D) 10'],
    difficulty: 2,
    explanation: 'h(4) = f(g(4)) = f(12) = 12 + 2 = 14',
  },

  // ── AP PRECALCULUS: POLYNOMIAL FUNCTIONS (6) ───────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Polynomial Functions',
    subtopic: 'Factoring and Roots',
    question_text: 'Which polynomial has roots at x = −1, x = 2, and x = 5?',
    answer_text: 'A',
    choices: ['A) (x+1)(x−2)(x−5)', 'B) (x−1)(x+2)(x+5)', 'C) (x+1)(x+2)(x−5)', 'D) (x−1)(x−2)(x+5)'],
    difficulty: 2,
    explanation: 'Roots r mean factor (x−r), so roots −1, 2, 5 give (x+1)(x−2)(x−5)',
  },
  {
    subject: 'ap_precalc',
    topic: 'Polynomial Functions',
    subtopic: 'End Behavior',
    question_text: 'What is the end behavior of f(x) = −2x³ + 5x?',
    answer_text: 'A',
    choices: ['A) Up left, down right', 'B) Down left, up right', 'C) Up both sides', 'D) Down both sides'],
    difficulty: 2,
    explanation: 'Leading term −2x³: odd degree with negative coefficient → up left, down right',
  },
  {
    subject: 'ap_precalc',
    topic: 'Polynomial Functions',
    subtopic: 'Degree and Zeros',
    question_text: 'How many real zeros can a degree-4 polynomial have at most?',
    answer_text: 'A',
    choices: ['A) 4', 'B) 3', 'C) 2', 'D) Infinite'],
    difficulty: 1,
    explanation: 'A degree-n polynomial has at most n real zeros',
  },
  {
    subject: 'ap_precalc',
    topic: 'Polynomial Functions',
    subtopic: 'Factoring and Roots',
    question_text: 'Factor completely: x³ − 8',
    answer_text: 'A',
    choices: ['A) (x−2)(x²+2x+4)', 'B) (x+2)(x²−2x+4)', 'C) (x−2)³', 'D) (x−2)(x+4)²'],
    difficulty: 3,
    explanation: 'Difference of cubes: a³−b³=(a−b)(a²+ab+b²) with a=x, b=2',
  },
  {
    subject: 'ap_precalc',
    topic: 'Polynomial Functions',
    subtopic: 'Multiplicity',
    question_text: 'What is the multiplicity of the root x = 3 in f(x) = (x−3)²(x+1)?',
    answer_text: 'A',
    choices: ['A) 2', 'B) 1', 'C) 3', 'D) 0'],
    difficulty: 2,
    explanation: 'The factor (x−3) appears twice, so the multiplicity is 2',
  },
  {
    subject: 'ap_precalc',
    topic: 'Polynomial Functions',
    subtopic: 'Factoring and Roots',
    question_text: 'Which of the following is a factor of x² − 5x + 6?',
    answer_text: 'A',
    choices: ['A) (x−2)', 'B) (x−6)', 'C) (x+3)', 'D) (x+2)'],
    difficulty: 1,
    explanation: 'x²−5x+6 = (x−2)(x−3), so (x−2) is a factor',
  },

  // ── AP PRECALCULUS: RATIONAL FUNCTIONS (5) ─────────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Rational Functions',
    subtopic: 'Vertical Asymptotes',
    question_text: 'Where is the vertical asymptote of f(x) = (x+1)/(x²−4)?',
    answer_text: 'A',
    choices: ['A) x = 2 and x = −2', 'B) x = 4', 'C) x = −1', 'D) y = 0'],
    difficulty: 2,
    explanation: 'Set denominator = 0: x²−4 = 0 → x = ±2',
  },
  {
    subject: 'ap_precalc',
    topic: 'Rational Functions',
    subtopic: 'Horizontal Asymptotes',
    question_text: 'What is the horizontal asymptote of f(x) = (3x²)/(x²+1)?',
    answer_text: 'A',
    choices: ['A) y = 3', 'B) y = 0', 'C) y = 1', 'D) No asymptote'],
    difficulty: 2,
    explanation: 'Same degree in numerator and denominator: ratio of leading coefficients = 3/1 = 3',
  },
  {
    subject: 'ap_precalc',
    topic: 'Rational Functions',
    subtopic: 'Holes',
    question_text: 'A hole exists at x = 2 in f(x) = (x²−4)/(x−2) because:',
    answer_text: 'A',
    choices: [
      'A) (x−2) cancels from both numerator and denominator',
      'B) The denominator equals zero at x = 2',
      'C) The numerator equals zero at x = 2',
      'D) The function is undefined everywhere',
    ],
    difficulty: 3,
    explanation: 'x²−4 = (x−2)(x+2), so (x−2) cancels — creating a hole, not an asymptote',
  },
  {
    subject: 'ap_precalc',
    topic: 'Rational Functions',
    subtopic: 'Domain and Range',
    question_text: 'What is the range restriction of f(x) = 1/x?',
    answer_text: 'A',
    choices: ['A) y ≠ 0', 'B) y > 0', 'C) y ≥ 1', 'D) All real numbers'],
    difficulty: 2,
    explanation: '1/x can never equal 0, so y ≠ 0',
  },
  {
    subject: 'ap_precalc',
    topic: 'Rational Functions',
    subtopic: 'Horizontal Asymptotes',
    question_text: 'For f(x) = (2x+1)/(x−3), as x → ∞, f(x) →?',
    answer_text: 'A',
    choices: ['A) 2', 'B) −1/3', 'C) 0', 'D) ∞'],
    difficulty: 2,
    explanation: 'Degree of numerator = degree of denominator: HA = 2/1 = 2',
  },

  // ── AP PRECALCULUS: EXPONENTIAL FUNCTIONS (5) ──────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Exponential Functions',
    subtopic: 'Solving Exponential Equations',
    question_text: 'Solve: 2^x = 32',
    answer_text: 'A',
    choices: ['A) 5', 'B) 4', 'C) 6', 'D) 16'],
    difficulty: 1,
    explanation: '32 = 2⁵, so x = 5',
  },
  {
    subject: 'ap_precalc',
    topic: 'Exponential Functions',
    subtopic: 'Growth and Decay',
    question_text: 'The function f(x) = 3·(1/2)^x represents:',
    answer_text: 'A',
    choices: ['A) Exponential decay', 'B) Exponential growth', 'C) Linear decay', 'D) Logarithmic growth'],
    difficulty: 1,
    explanation: 'Base 1/2 < 1, so this is exponential decay',
  },
  {
    subject: 'ap_precalc',
    topic: 'Exponential Functions',
    subtopic: 'Logarithms',
    question_text: 'What is log₂(64)?',
    answer_text: 'A',
    choices: ['A) 6', 'B) 32', 'C) 8', 'D) 4'],
    difficulty: 2,
    explanation: '2⁶ = 64, so log₂(64) = 6',
  },
  {
    subject: 'ap_precalc',
    topic: 'Exponential Functions',
    subtopic: 'Compound Interest',
    question_text: 'If $1000 is invested at 5% annual interest compounded annually, what is it worth after 2 years?',
    answer_text: 'A',
    choices: ['A) $1102.50', 'B) $1100', 'C) $1050', 'D) $1200'],
    difficulty: 2,
    explanation: 'A = 1000(1.05)² = 1000 × 1.1025 = $1102.50',
  },
  {
    subject: 'ap_precalc',
    topic: 'Exponential Functions',
    subtopic: 'Natural Logarithm',
    question_text: 'Solve: ln(x) = 3',
    answer_text: 'A',
    choices: ['A) x = e³', 'B) x = 3e', 'C) x = 10³', 'D) x = 3'],
    difficulty: 2,
    explanation: 'ln(x) = 3 means e³ = x',
  },

  // ── AP PRECALCULUS: TRIGONOMETRY (6) ───────────────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Trigonometry',
    subtopic: 'Unit Circle',
    question_text: 'What is sin(π/6)?',
    answer_text: 'A',
    choices: ['A) 1/2', 'B) √3/2', 'C) √2/2', 'D) 1'],
    difficulty: 1,
    explanation: 'sin(30°) = sin(π/6) = 1/2; standard unit circle value',
  },
  {
    subject: 'ap_precalc',
    topic: 'Trigonometry',
    subtopic: 'Period and Amplitude',
    question_text: 'What is the period of f(x) = sin(2x)?',
    answer_text: 'A',
    choices: ['A) π', 'B) 2π', 'C) π/2', 'D) 4π'],
    difficulty: 2,
    explanation: 'Period = 2π/|b| = 2π/2 = π',
  },
  {
    subject: 'ap_precalc',
    topic: 'Trigonometry',
    subtopic: 'Trig Identities',
    question_text: 'Which identity is correct?',
    answer_text: 'A',
    choices: ['A) sin²x + cos²x = 1', 'B) sin²x − cos²x = 1', 'C) sin²x + cos²x = 0', 'D) sinx·cosx = 1'],
    difficulty: 1,
    explanation: 'The Pythagorean identity is sin²x + cos²x = 1',
  },
  {
    subject: 'ap_precalc',
    topic: 'Trigonometry',
    subtopic: 'Unit Circle',
    question_text: 'What is tan(π/4)?',
    answer_text: 'A',
    choices: ['A) 1', 'B) 0', 'C) √3', 'D) 1/√3'],
    difficulty: 1,
    explanation: 'tan(45°) = sin(45°)/cos(45°) = (√2/2)/(√2/2) = 1',
  },
  {
    subject: 'ap_precalc',
    topic: 'Trigonometry',
    subtopic: 'Period and Amplitude',
    question_text: 'The amplitude of f(x) = 4cos(x) is:',
    answer_text: 'A',
    choices: ['A) 4', 'B) 2', 'C) 1', 'D) π'],
    difficulty: 1,
    explanation: 'Amplitude = |A| = |4| = 4 in y = A·cos(x)',
  },
  {
    subject: 'ap_precalc',
    topic: 'Trigonometry',
    subtopic: 'Unit Circle',
    question_text: 'What is cos(0)?',
    answer_text: 'A',
    choices: ['A) 1', 'B) 0', 'C) −1', 'D) Undefined'],
    difficulty: 1,
    explanation: 'The point (1, 0) is at angle 0 on the unit circle; cos(0) = 1',
  },

  // ── AP PRECALCULUS: TRANSFORMATIONS (4) ────────────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Transformations',
    subtopic: 'Shifts',
    question_text: 'If f(x) = x², what does f(x−3) + 2 represent?',
    answer_text: 'A',
    choices: ['A) Shift right 3, up 2', 'B) Shift left 3, up 2', 'C) Shift right 3, down 2', 'D) Shift left 3, down 2'],
    difficulty: 2,
    explanation: 'f(x−h)+k shifts right h and up k; h=3, k=2 → right 3, up 2',
  },
  {
    subject: 'ap_precalc',
    topic: 'Transformations',
    subtopic: 'Reflections',
    question_text: 'Which transformation reflects f(x) across the x-axis?',
    answer_text: 'A',
    choices: ['A) −f(x)', 'B) f(−x)', 'C) f(x) + 1', 'D) f(x+1)'],
    difficulty: 2,
    explanation: 'Multiplying by −1 outside reflects across the x-axis',
  },
  {
    subject: 'ap_precalc',
    topic: 'Transformations',
    subtopic: 'Stretches',
    question_text: 'g(x) = 2f(x) is a:',
    answer_text: 'A',
    choices: [
      'A) Vertical stretch by factor 2',
      'B) Horizontal stretch by factor 2',
      'C) Vertical compression by factor 2',
      'D) Horizontal compression by factor 2',
    ],
    difficulty: 2,
    explanation: 'Multiplying by 2 outside the function stretches vertically by factor 2',
  },
  {
    subject: 'ap_precalc',
    topic: 'Transformations',
    subtopic: 'Absolute Value',
    question_text: 'If f(x) = |x|, what is the vertex of g(x) = |x − 1| − 3?',
    answer_text: 'A',
    choices: ['A) (1, −3)', 'B) (−1, 3)', 'C) (1, 3)', 'D) (−1, −3)'],
    difficulty: 2,
    explanation: 'Vertex of |x−h|+k is at (h, k) = (1, −3)',
  },

  // ── AP PRECALCULUS: CONICS (3) ─────────────────────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Conics',
    subtopic: 'Circles',
    question_text: 'The equation x² + y² = 25 represents a circle with radius:',
    answer_text: 'A',
    choices: ['A) 5', 'B) 25', 'C) 10', 'D) 12.5'],
    difficulty: 1,
    explanation: 'x²+y²=r², so r = √25 = 5',
  },
  {
    subject: 'ap_precalc',
    topic: 'Conics',
    subtopic: 'Parabolas',
    question_text: 'Which equation represents a parabola opening upward?',
    answer_text: 'A',
    choices: ['A) y = x² + 3', 'B) x = y² + 3', 'C) x² + y² = 9', 'D) x²/4 + y²/9 = 1'],
    difficulty: 1,
    explanation: 'y = x² + 3 is a parabola with vertex (0,3) opening upward',
  },
  {
    subject: 'ap_precalc',
    topic: 'Conics',
    subtopic: 'Ellipses',
    question_text: 'The center of the ellipse (x−2)²/9 + (y+1)²/4 = 1 is:',
    answer_text: 'A',
    choices: ['A) (2, −1)', 'B) (−2, 1)', 'C) (9, 4)', 'D) (3, 2)'],
    difficulty: 3,
    explanation: 'Standard form (x−h)²/a² + (y−k)²/b² = 1 has center (h, k) = (2, −1)',
  },

  // ── AP PRECALCULUS: MODELING (3) ───────────────────────────────────────────
  {
    subject: 'ap_precalc',
    topic: 'Modeling',
    subtopic: 'Exponential Models',
    question_text: 'A population doubles every 5 years. If it starts at 1000, the model is:',
    answer_text: 'A',
    choices: ['A) P(t) = 1000·2^(t/5)', 'B) P(t) = 1000 + 2t', 'C) P(t) = 1000·(0.5)^t', 'D) P(t) = 2000t'],
    difficulty: 3,
    explanation: 'Doubling every 5 years: multiply by 2 for each 5-year period → 2^(t/5)',
  },
  {
    subject: 'ap_precalc',
    topic: 'Modeling',
    subtopic: 'Quadratic Models',
    question_text: 'A ball is thrown up with height h(t) = −16t² + 64t + 5. What is the maximum height?',
    answer_text: 'A',
    choices: ['A) 69 feet', 'B) 64 feet', 'C) 74 feet', 'D) 5 feet'],
    difficulty: 3,
    explanation: 'Vertex at t = 64/32 = 2; h(2) = −16(4) + 64(2) + 5 = −64 + 128 + 5 = 69',
  },
  {
    subject: 'ap_precalc',
    topic: 'Modeling',
    subtopic: 'Exponential Models',
    question_text: 'Which function best models a quantity that grows by 8% each year?',
    answer_text: 'A',
    choices: ['A) y = a·(1.08)^t', 'B) y = a + 0.08t', 'C) y = a·(0.08)^t', 'D) y = a·e^(0.8t)'],
    difficulty: 2,
    explanation: 'Percent growth uses y = a·(1 + r)^t; 8% growth → (1.08)^t',
  },

  // ── SAT MATH: ALGEBRA (10) ─────────────────────────────────────────────────
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Linear Equations',
    question_text: 'If 3x − 7 = 14, what is x?',
    answer_text: 'A',
    choices: ['A) 7', 'B) 3', 'C) 5', 'D) 9'],
    difficulty: 1,
    explanation: '3x = 21 → x = 7',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Systems of Equations',
    question_text: 'Solve the system: x + y = 10 and x − y = 4',
    answer_text: 'A',
    choices: ['A) x = 7, y = 3', 'B) x = 3, y = 7', 'C) x = 6, y = 4', 'D) x = 5, y = 5'],
    difficulty: 2,
    explanation: 'Adding: 2x = 14 → x = 7; y = 10 − 7 = 3',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Inequalities',
    question_text: 'Which inequality represents: twice a number minus 3 is at most 11?',
    answer_text: 'A',
    choices: ['A) 2n − 3 ≤ 11', 'B) 2n − 3 < 11', 'C) 2n + 3 ≤ 11', 'D) 2n − 3 ≥ 11'],
    difficulty: 1,
    explanation: '"At most" means ≤; "twice a number minus 3" is 2n − 3',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Exponent Rules',
    question_text: 'Simplify: (2x³y²)(3xy⁴)',
    answer_text: 'A',
    choices: ['A) 6x⁴y⁶', 'B) 5x⁴y⁶', 'C) 6x³y⁸', 'D) 6x⁴y⁸'],
    difficulty: 2,
    explanation: 'Multiply coefficients: 2×3=6. Add exponents: x^(3+1)=x⁴, y^(2+4)=y⁶',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Word Problems',
    question_text: 'A store sells notebooks for $3 each. If Maria spends $24, how many notebooks did she buy?',
    answer_text: 'A',
    choices: ['A) 8', 'B) 6', 'C) 12', 'D) 4'],
    difficulty: 1,
    explanation: '24 ÷ 3 = 8 notebooks',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Linear Equations',
    question_text: 'What is the slope of the line 4x − 2y = 8?',
    answer_text: 'A',
    choices: ['A) 2', 'B) 4', 'C) −2', 'D) 1/2'],
    difficulty: 2,
    explanation: 'Rewrite: 2y = 4x − 8 → y = 2x − 4; slope = 2',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Absolute Value Equations',
    question_text: 'If |x − 3| = 5, what are the solutions?',
    answer_text: 'A',
    choices: ['A) x = 8 or x = −2', 'B) x = 8 or x = 2', 'C) x = −8 or x = −2', 'D) x = 2 only'],
    difficulty: 2,
    explanation: 'x − 3 = 5 → x = 8; x − 3 = −5 → x = −2',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Linear Equations',
    question_text: 'A line passes through (0, −2) and (4, 6). What is its equation?',
    answer_text: 'A',
    choices: ['A) y = 2x − 2', 'B) y = 2x + 2', 'C) y = x − 2', 'D) y = 4x − 2'],
    difficulty: 2,
    explanation: 'Slope = (6−(−2))/(4−0) = 8/4 = 2; y-intercept = −2; y = 2x − 2',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Linear Equations',
    question_text: 'Solve: x/4 + 3 = 7',
    answer_text: 'A',
    choices: ['A) 16', 'B) 4', 'C) 28', 'D) 40'],
    difficulty: 1,
    explanation: 'x/4 = 4 → x = 16',
  },
  {
    subject: 'sat_math',
    topic: 'Algebra',
    subtopic: 'Simplifying Expressions',
    question_text: 'Which of the following is equivalent to 2(x + 3) − (x − 1)?',
    answer_text: 'A',
    choices: ['A) x + 7', 'B) x + 5', 'C) 3x + 7', 'D) x − 5'],
    difficulty: 1,
    explanation: '2x + 6 − x + 1 = x + 7',
  },

  // ── SAT MATH: ADVANCED MATH (8) ────────────────────────────────────────────
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Quadratic Equations',
    question_text: 'Solve x² − 5x + 6 = 0',
    answer_text: 'A',
    choices: ['A) x = 2 or x = 3', 'B) x = −2 or x = −3', 'C) x = 1 or x = 6', 'D) x = −1 or x = 6'],
    difficulty: 2,
    explanation: '(x−2)(x−3)=0 → x=2 or x=3',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Completing the Square',
    question_text: 'Complete the square: x² + 6x + ___ = (x + 3)²',
    answer_text: 'A',
    choices: ['A) 9', 'B) 3', 'C) 36', 'D) 6'],
    difficulty: 2,
    explanation: '(b/2)² = (6/2)² = 9',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Rational Expressions',
    question_text: 'If f(x) = x² − 4 and g(x) = x + 2, simplify f(x)/g(x) for x ≠ −2',
    answer_text: 'A',
    choices: ['A) x − 2', 'B) x + 2', 'C) x² − 2', 'D) x'],
    difficulty: 2,
    explanation: 'f(x)/g(x) = (x²−4)/(x+2) = (x−2)(x+2)/(x+2) = x−2',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Square Roots',
    question_text: 'The solutions to x² = 12 are:',
    answer_text: 'A',
    choices: ['A) x = ±2√3', 'B) x = ±6', 'C) x = ±4√3', 'D) x = ±√12'],
    difficulty: 2,
    explanation: 'x = ±√12 = ±√(4·3) = ±2√3',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Discriminant',
    question_text: 'For what value of k does x² + kx + 9 have exactly one real root?',
    answer_text: 'A',
    choices: ['A) 6 or −6', 'B) 3 or −3', 'C) 9 or −9', 'D) 18'],
    difficulty: 3,
    explanation: 'One root when discriminant = 0: k² − 36 = 0 → k = ±6',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Vertex Form',
    question_text: 'What is the vertex of y = (x − 2)² − 5?',
    answer_text: 'A',
    choices: ['A) (2, −5)', 'B) (−2, −5)', 'C) (2, 5)', 'D) (−2, 5)'],
    difficulty: 2,
    explanation: 'Vertex form y = (x−h)²+k → vertex (h, k) = (2, −5)',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Rational Expressions',
    question_text: 'Simplify: (x² − 9)/(x + 3) for x ≠ −3',
    answer_text: 'A',
    choices: ['A) x − 3', 'B) x + 3', 'C) x² − 3', 'D) x'],
    difficulty: 2,
    explanation: 'x²−9 = (x−3)(x+3); divide by (x+3) → x−3',
  },
  {
    subject: 'sat_math',
    topic: 'Advanced Math',
    subtopic: 'Exponential Equations',
    question_text: 'If 2^(2x) = 8, what is x?',
    answer_text: 'A',
    choices: ['A) 3/2', 'B) 3', 'C) 4', 'D) 1'],
    difficulty: 3,
    explanation: '2^(2x) = 2³ → 2x = 3 → x = 3/2',
  },

  // ── SAT MATH: GEOMETRY (6) ─────────────────────────────────────────────────
  {
    subject: 'sat_math',
    topic: 'Geometry',
    subtopic: 'Triangle Types',
    question_text: 'A triangle has sides 3, 4, and 5. What type of triangle is it?',
    answer_text: 'A',
    choices: ['A) Right', 'B) Acute', 'C) Obtuse', 'D) Equilateral'],
    difficulty: 1,
    explanation: '3²+4²=9+16=25=5²; satisfies Pythagorean theorem → right triangle',
  },
  {
    subject: 'sat_math',
    topic: 'Geometry',
    subtopic: 'Circles',
    question_text: 'The area of a circle with radius 6 is:',
    answer_text: 'A',
    choices: ['A) 36π', 'B) 12π', 'C) 6π', 'D) 18π'],
    difficulty: 1,
    explanation: 'A = πr² = π(6)² = 36π',
  },
  {
    subject: 'sat_math',
    topic: 'Geometry',
    subtopic: 'Parallel Lines',
    question_text: 'Two parallel lines are cut by a transversal. Alternate interior angles are:',
    answer_text: 'A',
    choices: ['A) Equal', 'B) Supplementary', 'C) Complementary', 'D) Adjacent'],
    difficulty: 1,
    explanation: 'Alternate interior angles formed by parallel lines and a transversal are congruent (equal)',
  },
  {
    subject: 'sat_math',
    topic: 'Geometry',
    subtopic: 'Pythagorean Theorem',
    question_text: 'A rectangle has length 8 and width 5. What is the diagonal?',
    answer_text: 'A',
    choices: ['A) √89', 'B) 13', 'C) 40', 'D) √40'],
    difficulty: 2,
    explanation: 'd = √(8²+5²) = √(64+25) = √89',
  },
  {
    subject: 'sat_math',
    topic: 'Geometry',
    subtopic: 'Volume',
    question_text: 'The volume of a cylinder with radius 3 and height 4 is:',
    answer_text: 'A',
    choices: ['A) 36π', 'B) 12π', 'C) 48π', 'D) 9π'],
    difficulty: 2,
    explanation: 'V = πr²h = π(9)(4) = 36π',
  },
  {
    subject: 'sat_math',
    topic: 'Geometry',
    subtopic: 'Special Triangles',
    question_text: 'In a 30-60-90 triangle with hypotenuse 10, the shorter leg is:',
    answer_text: 'A',
    choices: ['A) 5', 'B) 5√3', 'C) 10√3/3', 'D) 10'],
    difficulty: 2,
    explanation: 'Shorter leg = hypotenuse/2 = 10/2 = 5 (opposite the 30° angle)',
  },

  // ── SAT MATH: PROBLEM SOLVING & DATA ANALYSIS (6) ─────────────────────────
  {
    subject: 'sat_math',
    topic: 'Problem Solving & Data Analysis',
    subtopic: 'Rates',
    question_text: 'A car travels 240 miles in 4 hours. What is its average speed?',
    answer_text: 'A',
    choices: ['A) 60 mph', 'B) 80 mph', 'C) 50 mph', 'D) 70 mph'],
    difficulty: 1,
    explanation: 'Speed = distance/time = 240/4 = 60 mph',
  },
  {
    subject: 'sat_math',
    topic: 'Problem Solving & Data Analysis',
    subtopic: 'Percentages',
    question_text: 'If 40% of a number is 28, what is the number?',
    answer_text: 'A',
    choices: ['A) 70', 'B) 56', 'C) 40', 'D) 11.2'],
    difficulty: 1,
    explanation: '0.40 × n = 28 → n = 28/0.40 = 70',
  },
  {
    subject: 'sat_math',
    topic: 'Problem Solving & Data Analysis',
    subtopic: 'Statistics',
    question_text: 'The median of {3, 7, 8, 12, 15} is:',
    answer_text: 'A',
    choices: ['A) 8', 'B) 9', 'C) 7', 'D) 10'],
    difficulty: 1,
    explanation: 'Arranged in order, the middle value (3rd of 5) is 8',
  },
  {
    subject: 'sat_math',
    topic: 'Problem Solving & Data Analysis',
    subtopic: 'Percentages',
    question_text: 'A shirt costs $50 and is on sale for 20% off. What is the sale price?',
    answer_text: 'A',
    choices: ['A) $40', 'B) $30', 'C) $45', 'D) $60'],
    difficulty: 1,
    explanation: 'Discount = 0.20 × 50 = $10; Sale price = 50 − 10 = $40',
  },
  {
    subject: 'sat_math',
    topic: 'Problem Solving & Data Analysis',
    subtopic: 'Statistics',
    question_text: 'If the mean of 5 numbers is 14, what is their sum?',
    answer_text: 'A',
    choices: ['A) 70', 'B) 19', 'C) 14', 'D) 56'],
    difficulty: 1,
    explanation: 'Sum = mean × count = 14 × 5 = 70',
  },
  {
    subject: 'sat_math',
    topic: 'Problem Solving & Data Analysis',
    subtopic: 'Percentages',
    question_text: 'In a class of 30 students, 18 play sports. What percent play sports?',
    answer_text: 'A',
    choices: ['A) 60%', 'B) 40%', 'C) 18%', 'D) 30%'],
    difficulty: 1,
    explanation: '18/30 = 0.60 = 60%',
  },
]
