export type SATDomain = 'Algebra' | 'Advanced Math' | 'Problem Solving & Data Analysis' | 'Geometry & Trigonometry'
export type Difficulty = 'foundation' | 'standard' | 'advanced'

export interface SATTopic {
  id: string
  topicNumber: number
  domain: SATDomain
  skillArea: string
  lessonNumber: string
  title: string
  description: string
  difficulty: Difficulty
  estimatedMinutes: number
  keySkills: string[]
  satWeight: string
}

export const PART1_TOPICS: SATTopic[] = [
  // ─── Domain 1: Algebra ───────────────────────────────────────────────────────

  // Linear Equations in One Variable (alg-01 to alg-10)
  {
    id: 'alg-01',
    topicNumber: 1,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.1',
    title: 'Solving One-Step Equations',
    description:
      'Students learn to isolate a variable using a single inverse operation and verify their answer. Covers addition, subtraction, multiplication, and division equations.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Identify the variable',
      'Apply inverse operations',
      'Check solution by substituting back',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-02',
    topicNumber: 2,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.2',
    title: 'Solving Two-Step Equations',
    description:
      'Students apply two inverse operations in the correct order to isolate a variable. Focuses on the order of operations in reverse and solution verification.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Apply two inverse operations in sequence',
      'Handle addition/subtraction before multiplication/division',
      'Verify solution',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-03',
    topicNumber: 3,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.3',
    title: 'Multi-Step Equations with Distribution',
    description:
      'Students use the distributive property to expand expressions, then combine like terms before solving. Builds fluency with multi-step algebraic manipulation.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply the distributive property',
      'Combine like terms',
      'Solve multi-step equations',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-04',
    topicNumber: 4,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.4',
    title: 'Equations with Variables on Both Sides',
    description:
      'Students learn to collect variable terms on one side of the equation and constants on the other. Also covers special cases of no solution and infinite solutions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Move variables to one side',
      'Combine like terms across the equation',
      'Identify no-solution and all-real cases',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-05',
    topicNumber: 5,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.5',
    title: 'Equations with Fractions and Decimals',
    description:
      'Students eliminate fractions by multiplying through by the LCD and convert decimals for cleaner arithmetic. Builds comfort with equations that initially appear complex.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Multiply by LCD to clear fractions',
      'Convert decimals to fractions',
      'Solve and verify',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-06',
    topicNumber: 6,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.6',
    title: 'Absolute Value Equations',
    description:
      'Students set up two cases when solving equations involving absolute value and check each solution for validity. Covers the concept of extraneous solutions in absolute value context.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Set up two cases for absolute value',
      'Solve each case',
      'Check for extraneous solutions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-07',
    topicNumber: 7,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.7',
    title: 'Literal Equations and Formulas',
    description:
      'Students rearrange multi-variable formulas to solve for a specified variable, applying the same inverse-operation strategy as single-variable equations. Connects to physics and geometry applications.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Rearrange formulas to isolate a variable',
      'Apply to physics and geometry formulas',
      'Work with multi-variable equations',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-08',
    topicNumber: 8,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.8',
    title: 'Word Problems: Rate, Time, Distance',
    description:
      'Students translate rate-time-distance scenarios into linear equations and solve for an unknown quantity. Emphasizes defining variables clearly and interpreting the answer in context.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Set up d=rt equations',
      'Define variables from context',
      'Solve and interpret answers in context',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-09',
    topicNumber: 9,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.9',
    title: 'Word Problems: Age and Number Problems',
    description:
      'Students write algebraic expressions for age or number relationships described in words and solve the resulting equations. Develops careful reading and variable-definition skills.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Translate age relationships to equations',
      'Set up systems or single equations',
      'Solve and verify against problem conditions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-10',
    topicNumber: 10,
    domain: 'Algebra',
    skillArea: 'Linear Equations in One Variable',
    lessonNumber: '1.10',
    title: 'Multi-Step Word Problems with Linear Equations',
    description:
      'Students tackle complex real-world problems that require multiple equations or multi-step reasoning before arriving at a solution. Focuses on breaking problems into manageable parts and verifying against all conditions.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Break complex problems into steps',
      'Identify and define unknowns',
      'Check answer against all given conditions',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Linear Functions and Graphs (alg-11 to alg-20)
  {
    id: 'alg-11',
    topicNumber: 11,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.11',
    title: 'Slope and Rate of Change',
    description:
      'Students calculate slope from two points and interpret it as a constant rate of change. Covers all four slope cases: positive, negative, zero, and undefined.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Calculate slope from two points',
      'Interpret slope as rise over run',
      'Identify positive, negative, zero, and undefined slopes',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-12',
    topicNumber: 12,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.12',
    title: 'Slope-Intercept Form (y = mx + b)',
    description:
      'Students identify slope and y-intercept from an equation in slope-intercept form and use them to graph lines. Also covers writing the equation when slope and intercept are known.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Identify slope and y-intercept from equation',
      'Graph a line using slope and intercept',
      'Write the equation given slope and intercept',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-13',
    topicNumber: 13,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.13',
    title: 'Point-Slope Form',
    description:
      'Students write linear equations in point-slope form when given a point and a slope, then convert to slope-intercept form. Useful when the y-intercept is not directly given.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Write point-slope form from a point and slope',
      'Convert to slope-intercept form',
      'Use when y-intercept is not given',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-14',
    topicNumber: 14,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.14',
    title: 'Standard Form of Linear Equations (Ax + By = C)',
    description:
      'Students work with linear equations in standard form, converting to slope-intercept form and finding intercepts. Includes graphing directly from standard form using the intercepts.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Convert between standard and slope-intercept form',
      'Find x- and y-intercepts',
      'Graph from standard form',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-15',
    topicNumber: 15,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.15',
    title: 'Horizontal and Vertical Lines',
    description:
      'Students write and graph equations of horizontal and vertical lines, distinguishing between zero slope and undefined slope. Reinforces the connection between equation form and graphical appearance.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Write equations of horizontal lines (y = k)',
      'Write equations of vertical lines (x = h)',
      'Identify undefined slope vs. zero slope',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-16',
    topicNumber: 16,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.16',
    title: 'Parallel and Perpendicular Lines',
    description:
      'Students identify parallel lines by equal slopes and perpendicular lines by negative reciprocal slopes. Applies these relationships to write equations of lines through given points.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify parallel lines (equal slopes)',
      'Identify perpendicular lines (negative reciprocal slopes)',
      'Write equations of parallel/perpendicular lines through a point',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-17',
    topicNumber: 17,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.17',
    title: 'Writing Linear Equations from Graphs',
    description:
      'Students read slope and y-intercept directly from a graph to write the corresponding linear equation. Includes cases where the slope is a non-integer fraction.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read slope and intercept from a graph',
      'Write the equation of a graphed line',
      'Determine the equation when fractions are involved',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-18',
    topicNumber: 18,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.18',
    title: 'Writing Linear Equations from Two Points',
    description:
      'Students compute slope from two given points and use point-slope form to derive the equation, then simplify to slope-intercept form. Covers the full workflow from two points to a graphable equation.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Compute slope from two points',
      'Substitute into point-slope form',
      'Simplify to slope-intercept form',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-19',
    topicNumber: 19,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.19',
    title: 'Interpreting Slope and Intercept in Context',
    description:
      'Students interpret the slope as a rate of change and the y-intercept as an initial value within real-world scenarios. Prepares students for SAT questions that require contextual reasoning about linear models.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify what slope represents in a real-world situation',
      'Interpret the y-intercept as an initial value',
      'Answer SAT-style context questions about linear models',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-20',
    topicNumber: 20,
    domain: 'Algebra',
    skillArea: 'Linear Functions and Graphs',
    lessonNumber: '1.20',
    title: 'Linear vs. Nonlinear Functions',
    description:
      'Students distinguish linear from nonlinear functions using tables, graphs, and equations by checking for a constant rate of change. Builds conceptual understanding as a foundation for studying quadratic and exponential functions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify whether a table, graph, or equation is linear',
      'Distinguish between constant and varying rates of change',
      'Explain why a function is or is not linear',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Linear Inequalities (alg-21 to alg-28)
  {
    id: 'alg-21',
    topicNumber: 21,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.21',
    title: 'Solving One-Variable Inequalities',
    description:
      'Students solve linear inequalities, applying the sign-flip rule when multiplying or dividing by a negative number, and represent solutions on a number line or in interval notation.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Apply inequality rules (flip sign when multiplying/dividing by negative)',
      'Solve and graph on a number line',
      'Write solutions in interval notation',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-22',
    topicNumber: 22,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.22',
    title: 'Compound Inequalities (AND/OR)',
    description:
      'Students solve and graph compound inequalities joined by AND (intersection) or OR (union). Covers writing solutions in interval notation and interpreting them on a number line.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Solve compound inequalities with AND (intersection)',
      'Solve compound inequalities with OR (union)',
      'Graph compound inequalities on a number line',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-23',
    topicNumber: 23,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.23',
    title: 'Absolute Value Inequalities',
    description:
      'Students convert absolute value inequalities into equivalent compound inequalities and solve for the solution set. Includes both less-than and greater-than absolute value cases.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Solve |x| < a and |x| > a type inequalities',
      'Convert to compound inequalities',
      'Graph solutions on a number line',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-24',
    topicNumber: 24,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.24',
    title: 'Graphing Inequalities on a Number Line',
    description:
      'Students accurately graph inequality solutions using open and closed circles and directional shading on a number line. Builds the graphical interpretation skills needed for interpreting SAT answer choices.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Use open vs. closed circles correctly',
      'Shade the correct region',
      'Read inequality solutions from a number line graph',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-25',
    topicNumber: 25,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.25',
    title: 'Linear Inequalities in Two Variables',
    description:
      'Students graph linear inequalities on the coordinate plane by shading the appropriate half-plane above or below the boundary line. Uses a test point to confirm the correct region is shaded.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Graph a linear inequality on the coordinate plane',
      'Determine which half-plane to shade',
      'Use a test point to verify the shaded region',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-26',
    topicNumber: 26,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.26',
    title: 'Systems of Linear Inequalities',
    description:
      'Students graph two or more linear inequalities simultaneously and identify the feasible region where all inequalities are satisfied. Covers how to determine whether a specific point is in the solution region.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Graph two or more inequalities',
      'Identify the feasible region (intersection)',
      'Determine if a point satisfies the system',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-27',
    topicNumber: 27,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.27',
    title: 'Word Problems with Inequalities',
    description:
      'Students translate real-world constraints expressed in words into algebraic inequalities and solve for valid solution sets. Emphasizes correctly interpreting phrases like "at least," "at most," and "no more than."',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Translate constraints into inequalities',
      'Solve inequality word problems',
      'Interpret solutions in context',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-28',
    topicNumber: 28,
    domain: 'Algebra',
    skillArea: 'Linear Inequalities',
    lessonNumber: '1.28',
    title: 'Constraint Problems and Feasibility',
    description:
      'Students model real-world scenarios with multiple inequality constraints and determine which values or combinations are feasible. Builds skills for optimization-adjacent SAT questions involving boundaries.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Model real-world constraints with inequalities',
      'Determine if a solution is feasible',
      'Find boundary conditions of feasibility',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Systems of Linear Equations (alg-29 to alg-38)
  {
    id: 'alg-29',
    topicNumber: 29,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.29',
    title: 'Solving Systems by Substitution',
    description:
      'Students isolate one variable in an equation and substitute into the other equation to solve the system. Includes verification of the solution in both original equations.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Isolate one variable',
      'Substitute into the other equation',
      'Solve for both variables and verify',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-30',
    topicNumber: 30,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.30',
    title: 'Solving Systems by Elimination',
    description:
      'Students add or subtract equations to eliminate one variable, solving for the remaining one, then back-substitute. Covers multiplying equations to create matching coefficients before elimination.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Add or subtract equations to eliminate a variable',
      'Multiply equations to create matching coefficients',
      'Solve and verify the solution',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-31',
    topicNumber: 31,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.31',
    title: 'No Solution and Infinite Solutions',
    description:
      'Students recognize when a system has no solution (parallel lines) or infinitely many solutions (identical lines) by examining the structure of the equations. Covers how to determine the number of solutions without fully solving.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Recognize when lines are parallel (no solution)',
      'Recognize when lines are identical (infinite solutions)',
      'Determine the number of solutions from equations',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-32',
    topicNumber: 32,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.32',
    title: 'Systems from Tables and Graphs',
    description:
      'Students extract system equations from tables of values or read the solution as the intersection point on a graph. Develops flexibility in working with multiple representations of systems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read systems of equations from tables',
      'Find the intersection point from a graph',
      'Write systems from visual representations',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-33',
    topicNumber: 33,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.33',
    title: 'Word Problems: Mixture and Blend',
    description:
      'Students write two-equation systems to solve mixture problems involving concentrations, prices, or quantities. Focuses on correctly defining variables for each component and verifying the blend.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Set up mixture equations using concentrations',
      'Define variables for each component',
      'Solve and verify the blend',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-34',
    topicNumber: 34,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.34',
    title: 'Word Problems: Speed and Distance',
    description:
      'Students model two-traveler scenarios using d = rt for each traveler and set up a system based on meeting conditions or total distances. Develops careful problem setup for SAT travel word problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Set up systems using d = rt for multiple travelers',
      'Identify when travelers meet or are the same distance apart',
      'Solve for time and distance',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-35',
    topicNumber: 35,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.35',
    title: 'Word Problems: Investment and Interest',
    description:
      'Students write systems of equations to solve problems involving two investments at different interest rates. Applies simple interest formulas (I = Prt) and percentage equations to find unknown principal amounts.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Set up interest equations for two investments',
      'Use I = Prt or percentage equations',
      'Solve for principal amounts',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-36',
    topicNumber: 36,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.36',
    title: 'Choosing the Best Method for Systems',
    description:
      'Students analyze a system of equations and determine whether substitution or elimination is the more efficient approach. Builds strategic problem-solving habits for timed SAT conditions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Recognize when substitution is more efficient',
      'Recognize when elimination is more efficient',
      'Apply the best strategy to minimize steps',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-37',
    topicNumber: 37,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.37',
    title: 'Predicting Number of Solutions from Coefficients',
    description:
      'Students compare coefficient ratios to determine whether a system has zero, one, or infinitely many solutions without fully solving. Directly applicable to high-frequency SAT system identification questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Compare ratios of coefficients',
      'Determine if a system has 0, 1, or infinite solutions without solving',
      'Apply to SAT multiple-choice system problems',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-38',
    topicNumber: 38,
    domain: 'Algebra',
    skillArea: 'Systems of Linear Equations',
    lessonNumber: '1.38',
    title: 'Advanced System Word Problems',
    description:
      'Students translate complex multi-condition scenarios into systems of equations and select the most efficient solution method. Emphasizes interpreting solutions in real-world context and checking all conditions are satisfied.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Translate complex multi-condition problems into systems',
      'Choose efficient solution methods',
      'Interpret solutions in real-world context',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Ratios, Proportions, and Percentages (alg-39 to alg-50)
  {
    id: 'alg-39',
    topicNumber: 39,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.39',
    title: 'Ratios and Part-to-Part vs. Part-to-Whole',
    description:
      'Students distinguish between part-to-part and part-to-whole ratios and convert between the two forms. Covers writing ratios in fraction, colon, and word forms and using them to find unknown quantities.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Write ratios in multiple forms',
      'Convert between part-to-part and part-to-whole',
      'Use ratios to find unknown quantities',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-40',
    topicNumber: 40,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.40',
    title: 'Proportions and Cross-Multiplication',
    description:
      'Students set up and solve proportions by cross-multiplying, then use proportional reasoning to find missing values in tables, diagrams, and word problems.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Set up and solve proportions',
      'Apply cross-multiplication',
      'Use proportions to find missing values',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-41',
    topicNumber: 41,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.41',
    title: 'Percent of a Number',
    description:
      'Students convert between percent and decimal form and use multiplication to find a percent of a quantity or determine what percent one number is of another.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Convert between percent and decimal',
      'Find a percent of a quantity',
      'Find what percent one number is of another',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-42',
    topicNumber: 42,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.42',
    title: 'Percent Increase and Decrease',
    description:
      'Students calculate percent change using the formula (change / original) × 100 and distinguish between increase and decrease. Applies to SAT problems involving prices, populations, and data trends.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Calculate percent change using the formula',
      'Distinguish increase from decrease',
      'Apply to SAT price, population, and data problems',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-43',
    topicNumber: 43,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.43',
    title: 'Percent Error and Approximation',
    description:
      'Students calculate percent error between actual and estimated values and interpret its meaning in measurement contexts. Develops precision and estimation skills relevant to scientific and data SAT problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Calculate percent error from actual and estimated values',
      'Interpret percent error in context',
      'Apply to measurement and estimation problems',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-44',
    topicNumber: 44,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.44',
    title: 'Multi-Step Percent Problems',
    description:
      'Students apply successive percent changes and compute the overall percent change, avoiding the common error of simply adding individual percentages. Covers scenarios like price increases followed by discounts.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Chain multiple percent changes',
      'Avoid common errors with successive changes',
      'Compute overall percent change',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-45',
    topicNumber: 45,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.45',
    title: 'Markup, Discount, Tax, and Tip',
    description:
      'Students calculate final prices after applying markup, discount, tax, or tip and work backwards from a final price to the original value. Covers real-world consumer math scenarios common on the SAT.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Calculate final prices with markup or discount',
      'Add tax or tip to a total',
      'Work backwards from final price to original',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-46',
    topicNumber: 46,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.46',
    title: 'Direct Variation',
    description:
      'Students write and use the direct variation equation y = kx, find the constant of proportionality k from a pair of values, and apply the model to real-world proportional situations.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Write and use the equation y = kx',
      'Find the constant of variation k',
      'Apply direct variation to real-world problems',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-47',
    topicNumber: 47,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.47',
    title: 'Inverse Variation',
    description:
      'Students write and use the inverse variation equation y = k/x and find the constant of variation from given data. Contrasts inverse and direct variation to build discriminating judgment.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Write and use the equation y = k/x',
      'Find the constant k from a pair of values',
      'Distinguish direct from inverse variation',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-48',
    topicNumber: 48,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.48',
    title: 'Unit Rate and Dimensional Analysis',
    description:
      'Students convert between units using dimensional analysis and unit fractions, solving multi-step conversion problems. Builds systematic unit-tracking habits essential for SAT science-context problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Convert units using dimensional analysis',
      'Set up unit fractions',
      'Solve multi-step unit conversion problems',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-49',
    topicNumber: 49,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.49',
    title: 'Scale Factors and Scale Drawings',
    description:
      'Students interpret scale on maps and models and use proportions to calculate actual versus scale dimensions. Connects ratio and proportion skills to geometry and real-world applications.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Interpret scale on maps and models',
      'Calculate actual vs. scale dimensions',
      'Use proportions to solve scale problems',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'alg-50',
    topicNumber: 50,
    domain: 'Algebra',
    skillArea: 'Ratios, Proportions, and Percentages',
    lessonNumber: '1.50',
    title: 'Complex Multi-Step Proportional Reasoning',
    description:
      'Students combine ratio, percent, and proportion skills to solve challenging multi-step SAT-style problems. Focuses on planning the solution path, executing each step accurately, and verifying the final answer in context.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Combine ratio, percent, and proportion skills',
      'Solve multi-step SAT-style proportional problems',
      'Interpret and verify answers in context',
    ],
    satWeight: '~35% of SAT Math',
  },

  // ─── Domain 2: Advanced Math ─────────────────────────────────────────────────

  // Quadratic Equations (adv-01 to adv-14)
  {
    id: 'adv-01',
    topicNumber: 51,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.1',
    title: 'Factoring: Greatest Common Factor',
    description:
      'Students identify the greatest common factor of polynomial terms and factor it out to simplify expressions. Lays the groundwork for all subsequent factoring techniques.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Find GCF of polynomial terms',
      'Factor out GCF from expressions',
      'Verify by expanding',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-02',
    topicNumber: 52,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.2',
    title: 'Factoring: Difference of Two Squares',
    description:
      'Students recognize the a² − b² pattern and apply the (a + b)(a − b) identity to factor and solve quadratic equations. Builds pattern recognition critical for fast SAT factoring.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Recognize a²−b² pattern',
      'Apply (a+b)(a−b) factoring',
      'Use to solve quadratic equations',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-03',
    topicNumber: 53,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.3',
    title: 'Factoring Trinomials (a = 1)',
    description:
      'Students factor quadratic trinomials with a leading coefficient of 1 by finding two numbers that multiply to the constant and sum to the middle coefficient. Verifies using FOIL expansion.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Find factor pairs of the constant term',
      'Check sum of pairs equals middle coefficient',
      'Write in factored form and verify by FOIL',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-04',
    topicNumber: 54,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.4',
    title: 'Factoring Trinomials (a ≠ 1)',
    description:
      'Students factor trinomials where the leading coefficient is greater than 1 using the AC method or systematic trial-and-check. Builds the algebraic fluency needed for complex SAT quadratic problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Use AC method or guess-and-check',
      'Factor trinomials with leading coefficient > 1',
      'Verify by multiplying out',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-05',
    topicNumber: 55,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.5',
    title: 'Zero Product Property',
    description:
      'Students apply the Zero Product Property to set each factor of a factored quadratic equal to zero and solve for both roots. Connects factored form to the x-intercepts of a parabola.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Set each factor equal to zero',
      'Solve for both roots',
      'Interpret roots as x-intercepts',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-06',
    topicNumber: 56,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.6',
    title: 'Completing the Square',
    description:
      'Students add and subtract the perfect square term to rewrite a quadratic in vertex form and solve equations that do not factor easily. Underpins deriving the quadratic formula and understanding vertex form.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Add and subtract the perfect square term',
      'Rewrite in vertex form (x−h)²=k',
      'Solve quadratics that don\'t factor',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-07',
    topicNumber: 57,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.7',
    title: 'The Quadratic Formula',
    description:
      'Students apply the quadratic formula to find exact and decimal solutions for any quadratic equation in standard form. Covers identifying a, b, and c and handling both rational and irrational solutions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply x = (−b ± √(b²−4ac)) / 2a',
      'Identify a, b, c from standard form',
      'Find exact and decimal solutions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-08',
    topicNumber: 58,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.8',
    title: 'The Discriminant and Number of Solutions',
    description:
      'Students compute the discriminant b² − 4ac to determine whether a quadratic has two real solutions, one repeated solution, or no real solutions. Applies this analysis to SAT questions about the number of intersection points.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Compute b²−4ac',
      'Determine if solutions are 0, 1, or 2 real roots',
      'Interpret discriminant in context',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-09',
    topicNumber: 59,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.9',
    title: 'Vertex Form of a Parabola',
    description:
      'Students identify the vertex and direction of opening from a quadratic in vertex form y = a(x − h)² + k and convert from standard form by completing the square. Connects algebraic form to graphical features.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify vertex (h, k) from y = a(x−h)²+k',
      'Determine direction of opening from a',
      'Convert from standard to vertex form',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-10',
    topicNumber: 60,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.10',
    title: 'Converting Between Forms of a Quadratic',
    description:
      'Students move fluently among standard, vertex, and factored forms of quadratic equations, selecting the most useful form for each problem type. Builds the flexible algebraic thinking required for complex SAT quadratic items.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Move fluently between standard, vertex, and factored forms',
      'Identify best form for each problem type',
      'Apply conversions in SAT context questions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-11',
    topicNumber: 61,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.11',
    title: 'Reading Parabola Graphs',
    description:
      'Students identify the vertex, axis of symmetry, and intercepts of a parabola from its graph and match equations to graphical features. Develops visual-algebraic connection skills for SAT graph-matching questions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify vertex, axis of symmetry, and intercepts',
      'Determine equation from graph features',
      'Match equations to graphs',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-12',
    topicNumber: 62,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.12',
    title: 'Quadratic Word Problems: Projectile Motion',
    description:
      'Students set up and solve height functions for projectile motion, finding maximum height, time to reach maximum, and when the object lands. Covers interpreting vertex and zeros in a physical context.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Set up h(t) = −16t² + v₀t + h₀',
      'Find maximum height and time',
      'Determine when object hits ground',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-13',
    topicNumber: 63,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.13',
    title: 'Quadratic Word Problems: Area and Geometry',
    description:
      'Students translate geometric area conditions into quadratic equations and solve for unknown dimensions. Emphasizes rejecting negative solutions that have no geometric meaning.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Set up area equations as quadratics',
      'Solve for dimensions',
      'Verify positive solutions make geometric sense',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-14',
    topicNumber: 64,
    domain: 'Advanced Math',
    skillArea: 'Quadratic Equations',
    lessonNumber: '2.14',
    title: 'Systems: One Linear, One Quadratic',
    description:
      'Students solve mixed systems by substituting the linear equation into the quadratic and solving the resulting quadratic. Interprets the number of intersection points using the discriminant.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Substitute linear equation into quadratic',
      'Find intersection points',
      'Interpret the number of solutions geometrically',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Polynomial Operations (adv-15 to adv-24)
  {
    id: 'adv-15',
    topicNumber: 65,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.15',
    title: 'Adding and Subtracting Polynomials',
    description:
      'Students identify like terms by degree, add or subtract their coefficients, and simplify polynomial expressions. Builds foundational fluency for all higher-level polynomial work.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Identify like terms by degree',
      'Add/subtract coefficients of like terms',
      'Simplify polynomial expressions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-16',
    topicNumber: 66,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.16',
    title: 'Multiplying Polynomials (FOIL)',
    description:
      'Students multiply two binomials using FOIL and extend the technique to multiplying a trinomial by a binomial. Covers combining like terms in the resulting product.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Multiply two binomials using FOIL',
      'Combine like terms in the result',
      'Extend FOIL to trinomial × binomial',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-17',
    topicNumber: 67,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.17',
    title: 'Special Products: Perfect Square Trinomials',
    description:
      'Students apply the perfect square trinomial identities (a ± b)² to expand expressions quickly and recognize these patterns in reverse for factoring. Increases computational speed on the SAT.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply (a+b)² = a²+2ab+b²',
      'Apply (a−b)² = a²−2ab+b²',
      'Recognize and expand perfect square patterns',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-18',
    topicNumber: 68,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.18',
    title: 'Polynomial Long Division',
    description:
      'Students divide polynomials using the long division algorithm, finding both the quotient and the remainder. Expresses the result in the form quotient + remainder/divisor.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Set up polynomial long division',
      'Determine quotient and remainder',
      'Write result as quotient + remainder/divisor',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-19',
    topicNumber: 69,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.19',
    title: 'Synthetic Division',
    description:
      'Students apply the synthetic division shortcut when dividing a polynomial by a linear factor of the form (x − a). Uses the method to efficiently find quotients and test potential roots.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply synthetic division for linear divisors',
      'Find quotient and remainder efficiently',
      'Use to test potential factors',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-20',
    topicNumber: 70,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.20',
    title: 'Remainder Theorem',
    description:
      'Students state and apply the Remainder Theorem to find f(a) as the remainder when a polynomial is divided by (x − a). Enables rapid polynomial evaluation without full division.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'State and apply the Remainder Theorem',
      'Find f(a) as the remainder when dividing by (x−a)',
      'Use to evaluate polynomials quickly',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-21',
    topicNumber: 71,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.21',
    title: 'Factor Theorem and Zeros',
    description:
      'Students apply the Factor Theorem to determine whether a binomial (x − a) is a factor of a polynomial by checking if f(a) = 0. Uses this to find zeros and write polynomials in factored form.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'State the Factor Theorem',
      'Determine if (x−a) is a factor from f(a) = 0',
      'Find zeros by factoring',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-22',
    topicNumber: 72,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.22',
    title: 'Polynomial Functions and End Behavior',
    description:
      'Students determine the end behavior of polynomial functions from the leading term and use it to sketch a general graph shape. Applies this understanding to SAT graph-matching and behavior questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Determine end behavior from degree and leading coefficient',
      'Sketch general shape of polynomial graphs',
      'Apply to SAT graph-matching questions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-23',
    topicNumber: 73,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.23',
    title: 'Writing Polynomials from Zeros',
    description:
      'Students write linear factors from given zeros, multiply them together to obtain standard form, and account for multiplicity to understand graph behavior at each zero.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Write factors from given zeros',
      'Multiply factors to get standard form',
      'Use multiplicity to determine graph behavior at zeros',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-24',
    topicNumber: 74,
    domain: 'Advanced Math',
    skillArea: 'Polynomial Operations',
    lessonNumber: '2.24',
    title: 'Polynomial Identities and Factoring Patterns',
    description:
      'Students apply sum and difference of cubes formulas and recognize higher-degree factoring patterns. Develops the pattern recognition skills needed for the most challenging SAT polynomial items.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply sum/difference of cubes formulas',
      'Recognize factoring patterns in disguise',
      'Factor higher-degree polynomials strategically',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Rational Expressions and Equations (adv-25 to adv-32)
  {
    id: 'adv-25',
    topicNumber: 75,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.25',
    title: 'Simplifying Rational Expressions',
    description:
      'Students factor the numerator and denominator of rational expressions and cancel common factors to simplify. Always states domain restrictions for values that make the denominator zero.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Factor numerator and denominator',
      'Cancel common factors',
      'State domain restrictions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-26',
    topicNumber: 76,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.26',
    title: 'Multiplying and Dividing Rational Expressions',
    description:
      'Students factor all expressions before multiplying and convert division to multiplication by the reciprocal. Cancels common factors across numerators and denominators before multiplying.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Factor before multiplying',
      'Flip and multiply for division',
      'Cancel common factors across numerators and denominators',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-27',
    topicNumber: 77,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.27',
    title: 'Adding and Subtracting Rational Expressions',
    description:
      'Students find a common denominator for rational expressions with unlike denominators, rewrite each fraction, and combine the numerators. Simplifies the result and states any domain restrictions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Find the least common denominator (LCD)',
      'Rewrite fractions with LCD',
      'Combine numerators and simplify',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-28',
    topicNumber: 78,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.28',
    title: 'Solving Rational Equations',
    description:
      'Students multiply both sides of a rational equation by the LCD to clear all denominators and solve the resulting polynomial equation. Always checks solutions against domain restrictions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Multiply both sides by LCD to clear denominators',
      'Solve the resulting polynomial equation',
      'Check for extraneous solutions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-29',
    topicNumber: 79,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.29',
    title: 'Extraneous Solutions in Rational Equations',
    description:
      'Students identify values that make denominators zero before solving and systematically verify all solutions in the original equation. Explains the algebraic reason why extraneous solutions arise when multiplying by expressions containing variables.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify values that make denominators zero',
      'Verify solutions don\'t violate domain restrictions',
      'Explain why extraneous solutions arise',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-30',
    topicNumber: 80,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.30',
    title: 'Complex Fractions',
    description:
      'Students simplify complex fractions (fractions within fractions) by multiplying the entire expression by the compound LCD. Reduces multi-layered fractions to a single simplified rational expression.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Simplify fractions within fractions',
      'Multiply by the compound LCD',
      'Simplify to a single rational expression',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-31',
    topicNumber: 81,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.31',
    title: 'Rational Functions and Undefined Values',
    description:
      'Students find values where a rational function is undefined and distinguish between removable discontinuities (holes) and vertical asymptotes. Connects algebraic analysis to SAT graph and domain questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Find values where a rational function is undefined',
      'Identify holes vs. vertical asymptotes',
      'Apply to SAT graph and domain questions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-32',
    topicNumber: 82,
    domain: 'Advanced Math',
    skillArea: 'Rational Expressions and Equations',
    lessonNumber: '2.32',
    title: 'Applications: Work Rate Problems',
    description:
      'Students set up work rate equations using the formula 1/t₁ + 1/t₂ = 1/t_combined and solve for unknown time values. Interprets the combined rate in real-world cooperative work scenarios.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Set up work rate equation (1/t₁ + 1/t₂ = 1/t_combined)',
      'Solve for combined or individual time',
      'Interpret the answer in context',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Exponential and Radical Functions (adv-33 to adv-42)
  {
    id: 'adv-33',
    topicNumber: 83,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.33',
    title: 'Properties of Exponents Review',
    description:
      'Students review and apply the product, quotient, and power rules for exponents to simplify expressions with multiple exponent operations. Builds the fluency needed for exponential and radical work.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Apply product rule (aᵐ·aⁿ = aᵐ⁺ⁿ)',
      'Apply quotient and power rules',
      'Simplify expressions with multiple exponent rules',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-34',
    topicNumber: 84,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.34',
    title: 'Negative and Rational Exponents',
    description:
      'Students convert between negative exponents and their fraction equivalents and interpret rational exponents as radical expressions. Simplifies expressions combining negative and rational exponents.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Convert between negative exponents and fractions',
      'Interpret rational exponents as radicals',
      'Simplify expressions with rational exponents',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-35',
    topicNumber: 85,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.35',
    title: 'Exponential Growth and Decay',
    description:
      'Students write exponential models of the form y = ab^x, identify the initial value and growth or decay rate, and calculate values at specific time points. Applies to population, investment, and radioactive decay scenarios.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Write exponential models y = ab^x',
      'Identify growth (b>1) vs. decay (0<b<1)',
      'Calculate values at specific time points',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-36',
    topicNumber: 86,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.36',
    title: 'Compound Interest Formula',
    description:
      'Students apply the compound interest formula A = P(1 + r/n)^(nt) and distinguish it from simple interest. Solves for principal, rate, or time in compound interest scenarios.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply A = P(1 + r/n)^(nt)',
      'Distinguish from simple interest',
      'Solve for principal, rate, or time',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-37',
    topicNumber: 87,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.37',
    title: 'Interpreting Exponential Models in Context',
    description:
      'Students extract meaning from the initial value and growth or decay rate parameters of an exponential equation within a real-world context. Prepares for SAT interpretation questions about exponential models in science and finance.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify initial value and growth/decay rate from equation',
      'Interpret parameters in real-world context',
      'Answer SAT-style interpretation questions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-38',
    topicNumber: 88,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.38',
    title: 'Simplifying Radical Expressions',
    description:
      'Students simplify radical expressions by factoring out perfect squares (or perfect nth powers) and rationalize denominators. Builds the manipulation skills needed for solving radical equations.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Factor out perfect squares from radicands',
      'Simplify nth roots',
      'Rationalize denominators with radicals',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-39',
    topicNumber: 89,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.39',
    title: 'Solving Radical Equations',
    description:
      'Students isolate a radical expression and then raise both sides to the appropriate power to solve the equation. Always checks for extraneous solutions introduced by the squaring step.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Isolate the radical',
      'Square (or cube) both sides',
      'Check for extraneous solutions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-40',
    topicNumber: 90,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.40',
    title: 'Extraneous Solutions in Radical Equations',
    description:
      'Students identify when the squaring step introduces extraneous solutions and develop the habit of verifying every solution in the original equation. Explains the algebraic mechanism behind extraneous solutions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify when extraneous solutions appear',
      'Always verify solutions in the original equation',
      'Explain the algebraic reason for extraneous solutions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-41',
    topicNumber: 91,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.41',
    title: 'Comparing Linear, Quadratic, and Exponential Growth',
    description:
      'Students identify which growth model fits a given table or word problem by analyzing rates of change and ratios. Compares the long-term behavior of linear, quadratic, and exponential models.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify the growth type from a table',
      'Determine which type fits a word problem',
      'Compare long-term behavior of each growth type',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-42',
    topicNumber: 92,
    domain: 'Advanced Math',
    skillArea: 'Exponential and Radical Functions',
    lessonNumber: '2.42',
    title: 'Square Root and Cube Root Functions',
    description:
      'Students graph the basic square root and cube root functions with transformations and determine the domain of radical functions. Connects radical function graphs to their algebraic expressions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify domain of radical functions',
      'Graph y = √x and y = ∛x with transformations',
      'Solve equations involving radical functions',
    ],
    satWeight: '~35% of SAT Math',
  },

  // Functions (adv-43 to adv-50)
  {
    id: 'adv-43',
    topicNumber: 93,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.43',
    title: 'Function Notation and Evaluation',
    description:
      'Students evaluate a function f(x) at specific numerical and algebraic values and interpret function notation in real-world contexts. Distinguishes clearly between f(a) as a function output and f times a.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Evaluate f(x) at specific values',
      'Interpret function notation in context',
      'Distinguish between f(a) and f times a',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-44',
    topicNumber: 94,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.44',
    title: 'Domain and Range from Graphs and Tables',
    description:
      'Students read the domain and range from a graph or table and identify restrictions such as excluded values or bounded intervals. Writes domain and range in interval notation.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read domain and range from a graph',
      'Identify restrictions on domain',
      'Write domain and range in interval notation',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-45',
    topicNumber: 95,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.45',
    title: 'Composite Functions f(g(x))',
    description:
      'Students evaluate composite functions numerically and simplify them algebraically, working from the inside function outward. Interprets composite functions in applied contexts on the SAT.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Evaluate composite functions step-by-step',
      'Simplify algebraic composites',
      'Interpret composite functions in context',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-46',
    topicNumber: 96,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.46',
    title: 'Inverse Functions',
    description:
      'Students find inverse functions by swapping x and y and solving for y, then verify using the composition f(g(x)) = x. Interprets inverse functions as reversing the input-output relationship in real-world context.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Find inverse by swapping x and y',
      'Verify inverses using f(g(x)) = x',
      'Interpret inverse functions in real-world context',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-47',
    topicNumber: 97,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.47',
    title: 'Even and Odd Functions',
    description:
      'Students test functions algebraically for even or odd symmetry using the definitions f(−x) = f(x) and f(−x) = −f(x). Connects these algebraic definitions to graphical symmetry about the y-axis or origin.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Test for even functions (f(−x) = f(x))',
      'Test for odd functions (f(−x) = −f(x))',
      'Identify symmetry from the definition',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-48',
    topicNumber: 98,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.48',
    title: 'Transformations of Functions',
    description:
      'Students apply vertical and horizontal shifts, reflections, and stretches/compressions to function graphs and write the corresponding transformed equations from descriptions. Builds graphical fluency for SAT transformation questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply vertical/horizontal shifts',
      'Apply reflections and stretches',
      'Write transformed equations from graph descriptions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-49',
    topicNumber: 99,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.49',
    title: 'Piecewise Functions',
    description:
      'Students evaluate piecewise functions by selecting the correct rule for a given input and graph them with accurate domain boundaries. Writes piecewise functions from graphs or verbal descriptions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Evaluate piecewise functions at given inputs',
      'Graph piecewise functions with correct domains',
      'Write piecewise functions from graphs or descriptions',
    ],
    satWeight: '~35% of SAT Math',
  },
  {
    id: 'adv-50',
    topicNumber: 100,
    domain: 'Advanced Math',
    skillArea: 'Functions',
    lessonNumber: '2.50',
    title: 'Modeling with Functions',
    description:
      'Students choose the appropriate function type (linear, quadratic, exponential, etc.) to model a situation, write the function from data or context, and interpret and evaluate the model. Synthesizes all function knowledge for the most complex SAT modeling items.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Choose appropriate function type for a situation',
      'Write function models from data or context',
      'Interpret and evaluate function models',
    ],
    satWeight: '~35% of SAT Math',
  },
]
