// SAT Curriculum Part 2: Problem Solving & Data Analysis + Geometry & Trigonometry
// Topics 101–200 (50 PS&DA + 50 Geometry)

export type SATDomain =
  | 'Algebra'
  | 'Advanced Math'
  | 'Problem Solving & Data Analysis'
  | 'Geometry & Trigonometry'

export type Difficulty = 'foundation' | 'standard' | 'advanced'

export interface SATTopic {
  id: string
  topicNumber: number
  domain: SATDomain
  skillArea: string
  lessonNumber: string
  title: string
  description: string
  difficulty: Difficulty
  estimatedMinutes: number
  keySkills: string[]
  satWeight: string
}

export const PART2_TOPICS: SATTopic[] = [
  // ─── Domain 3: Problem Solving & Data Analysis ───────────────────────────

  // Ratios, Rates, and Unit Conversion (psda-01 to psda-08)
  {
    id: 'psda-01',
    topicNumber: 101,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.1',
    title: 'Ratios and Part-to-Part vs. Part-to-Whole',
    description:
      'Students learn to write and interpret ratios in fraction form, distinguishing between part-to-part and part-to-whole comparisons. They apply these concepts to find unknown quantities in practical contexts.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Write ratios in fraction form',
      'Convert between part-to-part and part-to-whole ratios',
      'Use ratios to find unknown quantities',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-02',
    topicNumber: 102,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.2',
    title: 'Unit Rates and Comparison Shopping',
    description:
      'Students calculate unit prices and rates to compare options and determine best value. They practice interpreting rates in everyday contexts such as fuel efficiency, wages, and grocery pricing.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Calculate unit price',
      'Compare rates to determine best value',
      'Interpret rates in context',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-03',
    topicNumber: 103,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.3',
    title: 'Dimensional Analysis and Unit Conversion',
    description:
      'Students use conversion fractions to change between metric and US customary units, chaining multiple conversions in a single setup. They verify that units cancel correctly to confirm dimensional consistency.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Set up unit conversion fractions',
      'Convert between metric and US customary units',
      'Perform multi-step conversions',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-04',
    topicNumber: 104,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.4',
    title: 'Multi-Step Rate Problems',
    description:
      'Students chain unit conversions and combine rates from multiple steps to solve complex real-world scenarios. They verify dimensional consistency throughout multi-step rate calculations.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Chain unit conversions',
      'Combine rates in real-world scenarios',
      'Verify dimensional consistency',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-05',
    topicNumber: 105,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.5',
    title: 'Proportional vs. Non-Proportional Relationships',
    description:
      'Students identify proportional relationships from tables and graphs by checking for a constant ratio, and distinguish them from additive (non-proportional) patterns. They apply this understanding to answer SAT questions about whether a relationship is proportional.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify proportional relationships from tables and graphs',
      'Verify constant ratio in proportional relationships',
      'Distinguish from additive (non-proportional) patterns',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-06',
    topicNumber: 106,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.6',
    title: 'Ratio Tables and Scaling',
    description:
      'Students complete ratio tables by scaling quantities up and down, applying the skill to recipe, map, and scale model problems. They recognize that every row in a ratio table represents an equivalent ratio.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Complete ratio tables',
      'Scale quantities up and down',
      'Apply to recipe, map, and model problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-07',
    topicNumber: 107,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.7',
    title: 'Complex Mixture Problems',
    description:
      'Students set up weighted mixture equations to find the concentration or amount of a component in a combined mixture. They verify that their answers satisfy all given conditions in multi-constraint problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Set up weighted mixture equations',
      'Solve for concentration or amount of a component',
      'Verify the answer satisfies all given conditions',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-08',
    topicNumber: 108,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Ratios, Rates, and Unit Conversion',
    lessonNumber: '3.8',
    title: 'Concentration and Dilution Problems',
    description:
      'Students model the effect of adding water or another solvent to a solution, using C₁V₁ = C₂V₂ reasoning to find new concentrations. They interpret numerical changes in concentration as water is added or solutions are combined.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Model adding water to a solution',
      'Use C₁V₁ = C₂V₂ reasoning',
      'Interpret concentration changes numerically',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Percentages and Growth (psda-09 to psda-16)
  {
    id: 'psda-09',
    topicNumber: 109,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.9',
    title: 'Finding Percent of a Quantity',
    description:
      'Students convert percents to decimals and multiply to find a percent of a quantity, and reverse the process to find what percent one number is of another. They also practice using benchmark percents (10%, 25%, 50%) for mental estimation.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Convert percent to decimal and multiply',
      'Find what percent one number is of another',
      'Work with benchmark percents mentally',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-10',
    topicNumber: 110,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.10',
    title: 'Percent Increase and Decrease in Context',
    description:
      'Students identify the original value and the amount of change to apply the percent change formula in realistic scenarios such as discounts, markups, and population change. They interpret the result in the context of the problem.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify original value and change',
      'Apply percent change formula',
      'Interpret results in real-world context',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-11',
    topicNumber: 111,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.11',
    title: 'Successive Percent Changes',
    description:
      'Students apply multiple percent changes in sequence by multiplying factors, avoiding the common error of simply adding or subtracting percents. They compute the overall percent change as a single multiplication factor.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply multiple percent changes in sequence',
      'Avoid the error of adding percents directly',
      'Compute overall percent change as a single factor',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-12',
    topicNumber: 112,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.12',
    title: 'Simple Interest in Context',
    description:
      'Students apply the formula I = Prt to solve for interest, principal, rate, or time in simple interest problems. They distinguish simple interest from compound interest and recognize when each model applies.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply I = Prt formula',
      'Solve for principal, rate, or time',
      'Distinguish from compound interest',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-13',
    topicNumber: 113,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.13',
    title: 'Exponential Growth and Decay Models',
    description:
      'Students write and apply the exponential model A = A₀(1 ± r)^t, identifying the initial value and growth or decay rate from context. They use the model to find doubling time or half-life in population and radioactive decay problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Write and apply A = A₀(1 ± r)^t',
      'Identify initial value and rate from context',
      'Determine doubling time or half-life',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-14',
    topicNumber: 114,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.14',
    title: 'Percent Error in Measurement',
    description:
      'Students apply the percent error formula to evaluate the accuracy of measurements in scientific and everyday contexts. They compare approximate to exact values and interpret the resulting percent error.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply percent error formula',
      'Interpret error in scientific and everyday contexts',
      'Compare approximate to exact values',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-15',
    topicNumber: 115,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.15',
    title: 'Interpreting Percent in Graphs and Tables',
    description:
      'Students read percentage data from bar and pie charts and calculate percent from raw data in tables. They compare relative frequencies across categories to answer SAT graph-interpretation questions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read percentage data from bar and pie charts',
      'Calculate percent from raw data in tables',
      'Compare relative frequencies',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-16',
    topicNumber: 116,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Percentages and Growth',
    lessonNumber: '3.16',
    title: 'Multi-Step Percent SAT Problems',
    description:
      'Students combine multiple percent skills in multi-step scenarios modeled on realistic SAT test contexts. They practice checking the reasonableness of answers to avoid common errors in complex percent problems.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Combine percent skills in multi-step scenarios',
      'Apply to realistic SAT test contexts',
      'Check reasonableness of answers',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Data Interpretation (psda-17 to psda-26)
  {
    id: 'psda-17',
    topicNumber: 117,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.17',
    title: 'Reading and Interpreting Bar Charts',
    description:
      'Students read values from bar heights and compare categories to answer quantitative questions about bar chart data. They calculate differences and totals from multiple bars in a chart.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Read values from bar heights',
      'Compare categories',
      'Calculate differences and totals from bar chart data',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-18',
    topicNumber: 118,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.18',
    title: 'Reading and Interpreting Line Graphs',
    description:
      'Students read values at specific points on a line graph, identify trends (increasing, decreasing, constant), and estimate values between labeled points. They use these skills to answer SAT questions about trends over time.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Read values at specific points on a line graph',
      'Identify trends (increasing, decreasing, constant)',
      'Estimate values between labeled points',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-19',
    topicNumber: 119,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.19',
    title: 'Interpreting Data Tables',
    description:
      'Students read data from rows and columns, calculate totals and percentages, and answer comparison questions using table data. They practice navigating complex tables efficiently under timed SAT conditions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read data from rows and columns',
      'Calculate totals and percentages',
      'Answer comparison questions using table data',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-20',
    topicNumber: 120,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.20',
    title: 'Two-Way Frequency Tables',
    description:
      'Students read joint, marginal, and conditional frequencies from two-way tables and complete partially-filled tables. They use two-way tables to answer probability and proportion questions on the SAT.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read joint, marginal, and conditional frequencies',
      'Complete partially-filled two-way tables',
      'Use tables to answer probability questions',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-21',
    topicNumber: 121,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.21',
    title: 'Relative Frequency and Marginal Distributions',
    description:
      'Students calculate relative frequencies from counts and interpret marginal distributions as row and column totals in two-way tables. They compare distributions across categories to draw meaningful conclusions from data.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Calculate relative frequencies from counts',
      'Interpret marginal distributions as row/column totals',
      'Compare distributions across categories',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-22',
    topicNumber: 122,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.22',
    title: 'Conditional Distributions in Two-Way Tables',
    description:
      'Students calculate conditional proportions within rows or columns and compare conditional distributions between groups. They interpret conditional distributions in real-world contexts to answer SAT survey questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Calculate conditional proportions within rows or columns',
      'Compare conditional distributions',
      'Interpret conditional distributions in context',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-23',
    topicNumber: 123,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.23',
    title: 'Histograms and Data Grouping',
    description:
      'Students read frequencies from histogram bars, identify the modal class, and estimate the median and range from the histogram. They recognize that histograms show grouped data and cannot reveal individual values.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read frequencies from histogram bars',
      'Identify the modal class',
      'Estimate median and range from a histogram',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-24',
    topicNumber: 124,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.24',
    title: 'Box Plots and Spread',
    description:
      'Students identify the five-number summary (minimum, Q1, median, Q3, maximum) from a box plot and calculate the IQR. They compare two distributions using side-by-side box plots to draw conclusions about center and spread.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify minimum, Q1, median, Q3, and maximum',
      'Calculate IQR from a box plot',
      'Compare two distributions using side-by-side box plots',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-25',
    topicNumber: 125,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.25',
    title: 'Dot Plots and Data Distribution',
    description:
      'Students read individual data values from a dot plot and calculate the mean and median directly from the display. They identify clusters, gaps, and outliers to describe the shape of the distribution.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read individual data values from a dot plot',
      'Calculate mean and median from a dot plot',
      'Identify clusters, gaps, and outliers',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-26',
    topicNumber: 126,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Data Interpretation',
    lessonNumber: '3.26',
    title: 'Choosing the Right Graph for the Data',
    description:
      'Students match graph types (bar, line, histogram, scatter, box, dot plot) to the data type and question being asked. They explain why one graph is more appropriate than another and apply this reasoning to SAT graph-interpretation questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Match graph type to data type and question',
      'Explain why one graph is more appropriate than another',
      'Apply to SAT graph-interpretation questions',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Statistics (psda-27 to psda-36)
  {
    id: 'psda-27',
    topicNumber: 127,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.27',
    title: 'Mean, Median, and Mode',
    description:
      'Students calculate the mean by summing values and dividing by count, find the median by ordering values, and identify the mode. They discuss when each measure of center is most appropriate for describing a data set.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Calculate mean by summing and dividing',
      'Find median by ordering values',
      'Identify mode and discuss when each measure is appropriate',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-28',
    topicNumber: 128,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.28',
    title: 'Weighted Averages',
    description:
      'Students calculate weighted means with given weights and set up equations to find missing values given a target weighted average. They apply weighted averages to grades, batting averages, and price problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Calculate weighted mean with given weights',
      'Set up and solve for missing values given a weighted average',
      'Apply to grades, batting averages, and price problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-29',
    topicNumber: 129,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.29',
    title: 'Range and Interquartile Range (IQR)',
    description:
      'Students calculate the range as max minus min and find Q1, Q3, and the IQR for a data set. They use the IQR to identify potential outliers using the 1.5 × IQR rule.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Calculate range as max − min',
      'Find Q1, Q3, and IQR',
      'Use IQR to identify outliers',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-30',
    topicNumber: 130,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.30',
    title: 'Standard Deviation (Conceptual)',
    description:
      'Students develop a conceptual understanding of standard deviation as a measure of spread and compare distributions by their standard deviations. They determine the effect of adding or removing values on the standard deviation without computing it by hand.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Interpret standard deviation as spread',
      'Compare distributions by their standard deviations',
      'Determine effect of adding/removing values on SD',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-31',
    topicNumber: 131,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.31',
    title: 'Outliers and Their Effect on Statistics',
    description:
      'Students identify outliers using the IQR rule and determine whether the mean or median is more affected by the presence of outliers. They predict the direction of skew introduced by extreme values in a distribution.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify outliers using IQR rule',
      'Determine whether mean or median is more affected by outliers',
      'Predict direction of skew from outliers',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-32',
    topicNumber: 132,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.32',
    title: 'Comparing Distributions',
    description:
      'Students compare the center, spread, and shape of two distributions using appropriate statistics and graphical displays. They draw meaningful conclusions from comparative analysis to answer SAT data questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Compare center, spread, and shape of two distributions',
      'Use appropriate statistics to make comparisons',
      'Draw conclusions from comparative analysis',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-33',
    topicNumber: 133,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.33',
    title: 'Normal Distribution Basics',
    description:
      'Students identify the key properties of a normal distribution (symmetric, bell-shaped) and apply the 68-95-99.7 empirical rule to interpret normally distributed data. They use these concepts to answer SAT questions about probability under a normal curve.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify properties of a normal distribution (symmetric, bell-shaped)',
      'Apply the 68-95-99.7 rule',
      'Interpret normally distributed data on the SAT',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-34',
    topicNumber: 134,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.34',
    title: 'Sampling Methods and Bias',
    description:
      'Students distinguish random from non-random sampling methods and identify common sources of bias including convenience sampling and voluntary response bias. They evaluate whether a given sample is representative of the population of interest.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Distinguish random from non-random sampling',
      'Identify sources of bias (convenience sample, voluntary response)',
      'Evaluate whether a sample is representative',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-35',
    topicNumber: 135,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.35',
    title: 'Drawing Conclusions from Studies',
    description:
      'Students distinguish between observational studies and controlled experiments to determine whether causation or only correlation can be inferred. They evaluate the appropriate scope of conclusions based on the study design.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Distinguish between observational study and experiment',
      'Determine if causation or correlation can be inferred',
      'Evaluate scope of conclusions',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-36',
    topicNumber: 136,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Statistics',
    lessonNumber: '3.36',
    title: 'Margin of Error (Conceptual)',
    description:
      'Students interpret the margin of error as a range of plausible values around a sample statistic and understand how sample size affects the margin of error. They apply this understanding to SAT survey and polling questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Interpret margin of error as a range of plausible values',
      'Understand effect of sample size on margin of error',
      'Apply to SAT survey and polling questions',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Probability (psda-37 to psda-44)
  {
    id: 'psda-37',
    topicNumber: 137,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.37',
    title: 'Basic Probability (Favorable/Total)',
    description:
      'Students write probability as a ratio of favorable to total equally likely outcomes and list sample spaces for simple events. They calculate the probability of a single event in straightforward scenarios.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Write probability as favorable/total outcomes',
      'List sample spaces for simple events',
      'Calculate probability of a single event',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-38',
    topicNumber: 138,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.38',
    title: 'Complementary Probability',
    description:
      'Students apply P(not A) = 1 − P(A) and use complementary counting to simplify probability calculations. They apply the complement rule especially to "at least one" probability questions.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Apply P(not A) = 1 − P(A)',
      'Use complementary counting to simplify problems',
      'Apply to "at least one" probability questions',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-39',
    topicNumber: 139,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.39',
    title: 'Independent Events (Multiplication Rule)',
    description:
      'Students verify whether events are independent and apply P(A and B) = P(A) × P(B) for independent events. They apply the multiplication rule to coin flips, dice rolls, and spinner problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Verify independence of events',
      'Apply P(A and B) = P(A) × P(B) for independent events',
      'Apply to coin, dice, and spinner problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-40',
    topicNumber: 140,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.40',
    title: 'Mutually Exclusive Events (Addition Rule)',
    description:
      'Students identify mutually exclusive events and apply the addition rule for both mutually exclusive and overlapping events. They correctly apply P(A or B) = P(A) + P(B) − P(A and B) when events can occur together.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify mutually exclusive events',
      'Apply P(A or B) = P(A) + P(B) for mutually exclusive events',
      'Apply P(A or B) = P(A) + P(B) − P(A and B) for overlapping events',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-41',
    topicNumber: 141,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.41',
    title: 'Conditional Probability',
    description:
      'Students apply the conditional probability formula P(A|B) = P(A and B)/P(B) and calculate conditional probabilities from two-way tables. They interpret conditional probability statements in real-world contexts.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply P(A|B) = P(A and B)/P(B)',
      'Calculate conditional probability from two-way tables',
      'Interpret conditional probability in context',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-42',
    topicNumber: 142,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.42',
    title: 'Expected Value',
    description:
      'Students calculate expected value as a weighted average of outcomes and apply it to games, insurance, and decision-making problems. They interpret expected value as the long-run average over many trials.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Calculate expected value as a weighted average of outcomes',
      'Apply to games, insurance, and decision-making problems',
      'Interpret expected value over many trials',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-43',
    topicNumber: 143,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.43',
    title: 'Probability from Two-Way Tables',
    description:
      'Students read joint probabilities from two-way frequency tables and calculate conditional and marginal probabilities. They use tables to find P(A and B) and P(A or B) for SAT data and probability questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Read joint probabilities from two-way frequency tables',
      'Calculate conditional and marginal probabilities',
      'Use tables to find P(A and B) and P(A or B)',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-44',
    topicNumber: 144,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Probability',
    lessonNumber: '3.44',
    title: 'Counting Techniques: Combinations and Permutations',
    description:
      'Students distinguish between permutations (order matters) and combinations (order does not matter) and apply the nPr and nCr formulas. They use these counting techniques to calculate probabilities for SAT questions.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Distinguish permutations (order matters) from combinations (order doesn\'t)',
      'Apply nPr and nCr formulas',
      'Use counting techniques to calculate probabilities',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Scatterplots and Regression (psda-45 to psda-50)
  {
    id: 'psda-45',
    topicNumber: 145,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Scatterplots and Regression',
    lessonNumber: '3.45',
    title: 'Reading Scatterplots',
    description:
      'Students read individual data points from a scatterplot, identify the overall direction of the relationship (positive, negative, or none), and estimate the strength of the relationship visually. They use these skills as the foundation for regression analysis.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Read individual data points from a scatterplot',
      'Identify the overall direction of the relationship',
      'Estimate the strength of a relationship visually',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-46',
    topicNumber: 146,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Scatterplots and Regression',
    lessonNumber: '3.46',
    title: 'Line of Best Fit: Equation and Meaning',
    description:
      'Students read the equation of a line of best fit and interpret the slope and y-intercept in the context of the problem. They use the equation to make predictions from a scatterplot.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Read the equation of the line of best fit',
      'Interpret slope and intercept in context',
      'Make predictions using the line of best fit',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-47',
    topicNumber: 147,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Scatterplots and Regression',
    lessonNumber: '3.47',
    title: 'Interpolation vs. Extrapolation',
    description:
      'Students define and distinguish interpolation (predicting within the data range) and extrapolation (predicting outside the data range), and identify when extrapolation may be unreliable. They make appropriate predictions from regression lines on the SAT.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Define and distinguish interpolation and extrapolation',
      'Identify when extrapolation may be unreliable',
      'Make appropriate predictions from regression lines',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-48',
    topicNumber: 148,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Scatterplots and Regression',
    lessonNumber: '3.48',
    title: 'Correlation vs. Causation',
    description:
      'Students define correlation and causation, and clearly articulate why correlation does not imply causation. They identify lurking variables that could explain observed correlations between two variables.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Define correlation and causation',
      'Explain why correlation does not imply causation',
      'Identify lurking variables that explain correlations',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-49',
    topicNumber: 149,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Scatterplots and Regression',
    lessonNumber: '3.49',
    title: 'Residuals and Goodness of Fit',
    description:
      'Students calculate residuals as the difference between actual and predicted values and interpret a residual plot to assess model fit. They use residual patterns to determine whether a linear model is appropriate.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Calculate residuals as actual minus predicted',
      'Interpret a residual plot',
      'Use residuals to assess model fit',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'psda-50',
    topicNumber: 150,
    domain: 'Problem Solving & Data Analysis',
    skillArea: 'Scatterplots and Regression',
    lessonNumber: '3.50',
    title: 'Exponential vs. Linear Regression Models',
    description:
      'Students determine whether a linear or exponential model is more appropriate for a given data set and interpret exponential regression equations in context. They apply these skills to SAT data analysis questions involving growth and decay.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Determine whether a linear or exponential model is more appropriate',
      'Interpret exponential regression equations',
      'Apply to SAT data analysis questions',
    ],
    satWeight: '~15% of SAT Math',
  },

  // ─── Domain 4: Geometry & Trigonometry ───────────────────────────────────

  // Area, Perimeter, and Volume (geo-01 to geo-10)
  {
    id: 'geo-01',
    topicNumber: 151,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.1',
    title: 'Perimeter of Polygons',
    description:
      'Students add all side lengths and apply perimeter formulas for rectangles and regular polygons to find total boundary length. They also work backwards from the perimeter to find missing side lengths.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Add all side lengths',
      'Apply perimeter formulas for rectangles and regular polygons',
      'Find missing sides given perimeter',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-02',
    topicNumber: 152,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.2',
    title: 'Area of Rectangles, Squares, and Parallelograms',
    description:
      'Students apply A = lw for rectangles and A = bh for parallelograms to calculate areas, and find missing dimensions when the area is given. They recognize that the height of a parallelogram is perpendicular to the base.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Apply A = lw for rectangles',
      'Apply A = bh for parallelograms',
      'Find missing dimensions given area',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-03',
    topicNumber: 153,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.3',
    title: 'Area of Triangles and Trapezoids',
    description:
      'Students apply A = ½bh for triangles and A = ½(b₁+b₂)h for trapezoids, and identify the correct base and height in various orientations. They apply these formulas to both standard and non-standard figure placements.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply A = ½bh for triangles',
      'Apply A = ½(b₁+b₂)h for trapezoids',
      'Identify base and height in various orientations',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-04',
    topicNumber: 154,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.4',
    title: 'Area of Composite Figures',
    description:
      'Students decompose composite shapes into simpler figures, then add or subtract their areas to find the total. They apply this skill to real-world problems such as floor plans, shaded regions, and irregular lot designs.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Decompose composite shapes into simpler figures',
      'Add or subtract areas of components',
      'Apply to real-world floor plan and design problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-05',
    topicNumber: 155,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.5',
    title: 'Circumference and Area of Circles',
    description:
      'Students apply C = 2πr and A = πr² to find circumference and area, and work backwards to find radius or diameter from a given circumference or area. They solve problems involving circles in real-world contexts.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply C = 2πr and A = πr²',
      'Find radius or diameter given circumference or area',
      'Solve problems involving circles in context',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-06',
    topicNumber: 156,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.6',
    title: 'Arc Length and Sector Area',
    description:
      'Students calculate arc length using (θ/360)·2πr and sector area using (θ/360)·πr², applying these formulas to real-world central angle problems. They work flexibly with central angles, radii, and arc or sector measurements.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Calculate arc length using (θ/360)·2πr',
      'Calculate sector area using (θ/360)·πr²',
      'Apply to real-world central angle problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-07',
    topicNumber: 157,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.7',
    title: 'Volume of Prisms and Cylinders',
    description:
      'Students apply V = Bh for prisms (where B is the base area) and V = πr²h for cylinders to find volume, and solve for missing dimensions when the volume is given. They recognize the base area as the key component in both formulas.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply V = Bh for prisms (B = base area)',
      'Apply V = πr²h for cylinders',
      'Solve for missing dimensions given volume',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-08',
    topicNumber: 158,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.8',
    title: 'Volume of Pyramids, Cones, and Spheres',
    description:
      'Students apply V = ⅓Bh for pyramids and cones and V = (4/3)πr³ for spheres to calculate volumes. They compare the volumes of related 3D figures and solve multi-step SAT problems involving these shapes.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply V = ⅓Bh for pyramids and cones',
      'Apply V = (4/3)πr³ for spheres',
      'Compare volumes of related 3D figures',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-09',
    topicNumber: 159,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.9',
    title: 'Surface Area of 3D Figures',
    description:
      'Students calculate the lateral and total surface area of prisms, cylinders, cones, and spheres by summing the areas of all faces or surfaces. They apply surface area to packaging and materials problems on the SAT.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Calculate lateral and total surface area of prisms and cylinders',
      'Calculate surface area of cones and spheres',
      'Apply to packaging and materials problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-10',
    topicNumber: 160,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Area, Perimeter, and Volume',
    lessonNumber: '4.10',
    title: 'Scale Factor and Its Effect on Area and Volume',
    description:
      'Students determine how area and volume change when linear dimensions are scaled by a factor k, applying the rules that area scales by k² and volume scales by k³. They use these relationships to solve SAT proportion problems involving similar figures.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Determine how area changes when linear dimensions scale (×k² for area)',
      'Determine how volume changes (×k³ for volume)',
      'Apply to similar figures and SAT proportion problems',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Triangle Properties (geo-11 to geo-20)
  {
    id: 'geo-11',
    topicNumber: 161,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.11',
    title: 'Triangle Angle Sum Theorem',
    description:
      'Students apply the triangle angle sum theorem (angles sum to 180°) to find missing angles in a triangle and multi-triangle diagrams. They use algebra to set up and solve angle equations in labeled figures.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Apply \'angles sum to 180°\'',
      'Find missing angles in a triangle',
      'Apply to multi-triangle diagrams',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-12',
    topicNumber: 162,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.12',
    title: 'Exterior Angle Theorem',
    description:
      'Students state and apply the exterior angle theorem — that an exterior angle equals the sum of the two non-adjacent interior angles — to find exterior and interior angles in triangle diagrams. They apply this theorem to multi-step SAT geometry problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'State that exterior angle equals sum of non-adjacent interior angles',
      'Find exterior and interior angles',
      'Apply to SAT diagram problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-13',
    topicNumber: 163,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.13',
    title: 'Isosceles and Equilateral Triangle Properties',
    description:
      'Students identify the base angles theorem for isosceles triangles and calculate all angles in equilateral triangles. They find missing sides and angles using the symmetry properties of these special triangles.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify base angles theorem for isosceles triangles',
      'Calculate all angles in equilateral triangles',
      'Find missing sides and angles using symmetry',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-14',
    topicNumber: 164,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.14',
    title: 'The Pythagorean Theorem',
    description:
      'Students apply a² + b² = c² to find missing sides of right triangles and identify whether three given lengths form a right triangle. They recognize common Pythagorean triples (3-4-5, 5-12-13) to solve problems efficiently.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply a² + b² = c²',
      'Find missing sides of right triangles',
      'Identify whether three lengths form a right triangle',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-15',
    topicNumber: 165,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.15',
    title: 'Pythagorean Theorem in Context',
    description:
      'Students apply the Pythagorean theorem to solve for diagonals, heights, and distances in real-world and geometric contexts. They set up the theorem from word problem descriptions and interpret the hypotenuse in context.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply to diagonal, height, and distance problems',
      'Set up the theorem from word problem descriptions',
      'Interpret the hypotenuse in real-world contexts',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-16',
    topicNumber: 166,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.16',
    title: '45-45-90 Special Right Triangles',
    description:
      'Students apply the 1:1:√2 side ratio of 45-45-90 triangles to find a leg or hypotenuse given one known side. They recognize 45-45-90 triangles from SAT diagrams and use this pattern to avoid unnecessary calculator work.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply sides in ratio 1:1:√2',
      'Find leg or hypotenuse given one side',
      'Recognize 45-45-90 triangles from SAT diagrams',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-17',
    topicNumber: 167,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.17',
    title: '30-60-90 Special Right Triangles',
    description:
      'Students apply the 1:√3:2 side ratio of 30-60-90 triangles to find missing sides given any one side. They correctly identify the short leg, long leg, and hypotenuse in various orientations of this special triangle.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply sides in ratio 1:√3:2',
      'Find missing sides given one side',
      'Distinguish short leg, long leg, and hypotenuse',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-18',
    topicNumber: 168,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.18',
    title: 'Triangle Inequality Theorem',
    description:
      'Students state that the sum of any two sides of a triangle must exceed the third side and use this theorem to determine possible side lengths. They apply the triangle inequality to SAT questions asking for the range of possible side lengths.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'State that sum of any two sides must exceed the third',
      'Determine possible side lengths for a triangle',
      'Apply to SAT range questions',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-19',
    topicNumber: 169,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.19',
    title: 'Medians, Altitudes, and Midsegments',
    description:
      'Students identify medians and their point of concurrency (centroid), apply the midsegment theorem (midsegment is half the length of the parallel base), and use altitudes to find area in different orientations. They apply these relationships to SAT multi-step problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Identify medians and their intersection (centroid)',
      'Apply midsegment theorem (half the base)',
      'Use altitudes to find area in different orientations',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-20',
    topicNumber: 170,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Triangle Properties',
    lessonNumber: '4.20',
    title: 'Triangle Proportionality Theorem',
    description:
      'Students apply the side splitter theorem and solve for segment lengths in triangles divided by a line parallel to one side. They apply the proportionality theorem to SAT problems involving parallel lines cutting across triangles.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply the side splitter theorem',
      'Solve for segment lengths in divided triangles',
      'Apply to SAT parallel lines and triangle problems',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Similarity and Congruence (geo-21 to geo-26)
  {
    id: 'geo-21',
    topicNumber: 171,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Similarity and Congruence',
    lessonNumber: '4.21',
    title: 'Similar Triangles: AA, SAS, SSS',
    description:
      'Students state and apply the AA, SAS, and SSS similarity criteria and use proportional corresponding sides to set up equations. They find missing sides in similar triangles by writing and solving proportion equations.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'State and apply AA similarity criterion',
      'Use proportional sides to set up equations',
      'Find missing sides in similar triangles',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-22',
    topicNumber: 172,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Similarity and Congruence',
    lessonNumber: '4.22',
    title: 'Proportions in Similar Figures',
    description:
      'Students write proportion equations from corresponding sides of similar figures and solve for missing lengths. They apply proportional reasoning to indirect measurement situations such as shadows and mirrors.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Write proportion equations from corresponding sides',
      'Solve for missing lengths',
      'Apply to shadows, mirrors, and indirect measurement',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-23',
    topicNumber: 173,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Similarity and Congruence',
    lessonNumber: '4.23',
    title: 'Scale Factors in Similar Polygons',
    description:
      'Students find the scale factor from corresponding sides of similar polygons and apply it to calculate perimeter ratios (equal to the scale factor) and area ratios (equal to the scale factor squared). They use these relationships to solve SAT problems efficiently.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Find scale factor from corresponding sides',
      'Calculate perimeter ratio (= scale factor)',
      'Calculate area ratio (= scale factor squared)',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-24',
    topicNumber: 174,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Similarity and Congruence',
    lessonNumber: '4.24',
    title: 'Congruent Triangles and CPCTC',
    description:
      'Students state the SAS, ASA, and SSS congruence criteria and apply CPCTC (Corresponding Parts of Congruent Triangles are Congruent) to conclude that corresponding parts are equal. They use congruence to find missing measurements in geometric figures.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'State SAS, ASA, SSS congruence',
      'Apply CPCTC to conclude corresponding parts are equal',
      'Use congruence to find missing measurements',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-25',
    topicNumber: 175,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Similarity and Congruence',
    lessonNumber: '4.25',
    title: 'Proportional Segment Theorem',
    description:
      'Students apply segment proportionality when lines are parallel and set up and solve proportion equations from transversal diagrams. They apply this theorem to divided triangles and multi-transversal SAT problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply segment proportionality when lines are parallel',
      'Set up and solve proportion equations',
      'Apply to divided triangles and transversals',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-26',
    topicNumber: 176,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Similarity and Congruence',
    lessonNumber: '4.26',
    title: 'Solving Problems with Similar Triangles',
    description:
      'Students identify similar triangles embedded in complex diagrams and set up and solve multi-step proportion equations to find unknown lengths. They verify the reasonableness of solutions by checking that ratios are consistent.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Identify similar triangles in complex diagrams',
      'Set up and solve multi-step proportions',
      'Verify reasonableness of solutions',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Angle Relationships (geo-27 to geo-32)
  {
    id: 'geo-27',
    topicNumber: 177,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Angle Relationships',
    lessonNumber: '4.27',
    title: 'Complementary and Supplementary Angles',
    description:
      'Students define complementary angles (sum = 90°) and supplementary angles (sum = 180°) and find missing angles in complementary or supplementary pairs. They apply these definitions to SAT angle problems involving diagrams.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'Define complementary (sum = 90°) and supplementary (sum = 180°)',
      'Find missing angles in complementary/supplementary pairs',
      'Apply to SAT angle problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-28',
    topicNumber: 178,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Angle Relationships',
    lessonNumber: '4.28',
    title: 'Vertical Angles and Linear Pairs',
    description:
      'Students state that vertical angles are equal and that angles forming a linear pair are supplementary, then apply these relationships to find angle measures in intersecting line diagrams. They use algebra to solve for variables in multi-angle problems.',
    difficulty: 'foundation',
    estimatedMinutes: 15,
    keySkills: [
      'State that vertical angles are equal',
      'Apply linear pair theorem (supplementary)',
      'Find angle measures in intersecting lines',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-29',
    topicNumber: 179,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Angle Relationships',
    lessonNumber: '4.29',
    title: 'Parallel Lines and Transversals',
    description:
      'Students identify the pairs of angles formed when a transversal crosses parallel lines and apply the corresponding, alternate interior, and co-interior angle theorems. They use angle evidence to determine whether two lines are parallel.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Identify pairs of angles formed by a transversal',
      'Apply corresponding, alternate interior, and co-interior angle theorems',
      'Determine if lines are parallel from angle evidence',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-30',
    topicNumber: 180,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Angle Relationships',
    lessonNumber: '4.30',
    title: 'Corresponding, Alternate Interior, and Co-Interior Angles',
    description:
      'Students correctly name angle pairs formed by parallel lines and a transversal, apply equal and supplementary relationships, and use algebra to find angle measures. They build fluency with all angle pair types as a foundation for more complex geometry problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Name angle pairs correctly',
      'Apply equal/supplementary relationships',
      'Use algebra to find angle measures',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-31',
    topicNumber: 181,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Angle Relationships',
    lessonNumber: '4.31',
    title: 'Interior and Exterior Angles of Polygons',
    description:
      'Students apply the interior angle sum formula (n−2)×180° to find the total or each interior angle in a regular polygon, and calculate exterior angles using 360°/n. They apply these formulas to SAT questions about regular and irregular polygons.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply interior angle sum formula: (n−2)×180°',
      'Find each interior angle in a regular polygon',
      'Calculate exterior angles using 360°/n',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-32',
    topicNumber: 182,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Angle Relationships',
    lessonNumber: '4.32',
    title: 'Angles in Circles (Inscribed and Central)',
    description:
      'Students apply the central angle theorem (central angle equals arc measure) and the inscribed angle theorem (inscribed angle equals half the arc measure) to find arc and angle measures in circle diagrams. They use these theorems in multi-step SAT circle problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply central angle theorem (= arc measure)',
      'Apply inscribed angle theorem (= ½ arc measure)',
      'Find arc and angle measures in circle diagrams',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Coordinate Geometry (geo-33 to geo-40)
  {
    id: 'geo-33',
    topicNumber: 183,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.33',
    title: 'Distance Formula',
    description:
      'Students apply d = √((x₂−x₁)² + (y₂−y₁)²) to find the distance between two points on the coordinate plane. They use the distance formula in perimeter and segment length problems on the SAT.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply d = √((x₂−x₁)² + (y₂−y₁)²)',
      'Find distance between two points on the coordinate plane',
      'Apply to perimeter and length problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-34',
    topicNumber: 184,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.34',
    title: 'Midpoint Formula',
    description:
      'Students apply the midpoint formula M = ((x₁+x₂)/2, (y₁+y₂)/2) to find midpoints and missing endpoints of segments. They use the midpoint formula in segment bisector and coordinate geometry proof problems.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply M = ((x₁+x₂)/2, (y₁+y₂)/2)',
      'Find midpoints and missing endpoints',
      'Apply to segment bisectors and geometric proofs',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-35',
    topicNumber: 185,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.35',
    title: 'Slope and Collinearity',
    description:
      'Students calculate slope between pairs of points and use equal slopes to determine if three points are collinear. They apply slope calculations to determine the shape (parallelogram, rectangle, etc.) of quadrilaterals on the coordinate plane.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Calculate slope between points',
      'Determine if three points are collinear',
      'Apply slope to determine shape of quadrilaterals',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-36',
    topicNumber: 186,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.36',
    title: 'Equation of a Circle',
    description:
      'Students write the standard form equation (x−h)² + (y−k)² = r² of a circle and identify the center and radius. They complete the square to convert the general form of a circle equation to standard form.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Write (x−h)² + (y−k)² = r²',
      'Identify center and radius from equation',
      'Complete the square to find center and radius',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-37',
    topicNumber: 187,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.37',
    title: 'Translations and Reflections on the Coordinate Plane',
    description:
      'Students apply translations using the rule (x+a, y+b) and reflections across the x-axis, y-axis, and the line y=x to find the image of points and figures. They use these transformation rules to solve SAT coordinate geometry questions.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Apply translation (x+a, y+b)',
      'Apply reflections across x-axis, y-axis, and y=x',
      'Find the image of a point or figure after a transformation',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-38',
    topicNumber: 188,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.38',
    title: 'Rotations and Symmetry',
    description:
      'Students apply 90°, 180°, and 270° rotations about the origin and identify lines and points of symmetry in figures. They determine the rotation angle that maps a pre-image onto its image on the coordinate plane.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply 90°, 180°, and 270° rotations about the origin',
      'Identify lines and points of symmetry',
      'Determine rotation angle from pre-image and image',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-39',
    topicNumber: 189,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.39',
    title: 'Partitioning a Line Segment',
    description:
      'Students divide a segment in a given ratio using the section formula and apply this technique to find points that partition a segment in a specific ratio. They use this skill to answer SAT questions about points on directed line segments.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Divide a segment in a given ratio',
      'Apply the section formula',
      'Apply to SAT questions about finding points on segments',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-40',
    topicNumber: 190,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Coordinate Geometry',
    lessonNumber: '4.40',
    title: 'Coordinate Geometry Proofs (Intro)',
    description:
      'Students use coordinates to verify properties of geometric figures such as parallelograms and rectangles, applying slope and distance as tools. They write logical coordinate geometry arguments to support their conclusions.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Use coordinates to verify properties of geometric figures',
      'Prove parallelograms and rectangles using slope and distance',
      'Write logical coordinate geometry arguments',
    ],
    satWeight: '~15% of SAT Math',
  },

  // Trigonometry (geo-41 to geo-50)
  {
    id: 'geo-41',
    topicNumber: 191,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.41',
    title: 'Trig Ratios: SOHCAHTOA',
    description:
      'Students define sine, cosine, and tangent in terms of opposite, adjacent, and hypotenuse sides of a right triangle. They correctly identify the relevant sides for a given angle and write trig ratios from labeled diagrams.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Define sin, cos, and tan in right triangles',
      'Identify opposite, adjacent, and hypotenuse correctly',
      'Write trig ratios from labeled diagrams',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-42',
    topicNumber: 192,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.42',
    title: 'Finding Missing Sides with Trigonometry',
    description:
      'Students set up trig equations to find unknown sides in right triangles and use calculator values or exact trig ratios to solve them. They apply these techniques to SAT diagram and word problems involving right triangles.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Set up trig equations to find unknown sides',
      'Use calculator or exact values for trig ratios',
      'Apply to SAT diagram and word problems',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-43',
    topicNumber: 193,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.43',
    title: 'Finding Missing Angles with Inverse Trig',
    description:
      'Students apply sin⁻¹, cos⁻¹, and tan⁻¹ to find missing angles in right triangles from known side ratios. They interpret angle measures in both degree and radian contexts as required by SAT problems.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply sin⁻¹, cos⁻¹, tan⁻¹ to find angles',
      'Set up inverse trig equations from given sides',
      'Interpret angle measures in degree and radian contexts',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-44',
    topicNumber: 194,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.44',
    title: 'Trigonometry in Real-World Word Problems',
    description:
      'Students draw and label diagrams from word problem descriptions, set up trig equations to model the situation, and solve and interpret answers in context. They practice translating verbal geometry descriptions into mathematical models.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Draw and label diagrams from word problems',
      'Set up trig equations from descriptions',
      'Solve and interpret answers in context',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-45',
    topicNumber: 195,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.45',
    title: 'Complementary Angle Trig Identity: sin θ = cos(90°−θ)',
    description:
      'Students state and apply the co-function identity sin θ = cos(90°−θ) and recognize when this identity simplifies SAT problems. They prove the identity using the relationship between complementary angles in a right triangle.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'State and apply the co-function identity',
      'Recognize when this identity simplifies SAT problems',
      'Prove the identity using complementary angles in a right triangle',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-46',
    topicNumber: 196,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.46',
    title: 'Degrees to Radians Conversion',
    description:
      'Students convert angle measures from degrees to radians using the factor π/180 and from radians to degrees using 180/π. They recognize the radian equivalents of common angles such as 30°, 45°, 60°, 90°, and 180°.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Convert degrees to radians using π/180',
      'Convert radians to degrees using 180/π',
      'Recognize common angles in both units',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-47',
    topicNumber: 197,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.47',
    title: 'Arc Length with Radian Measure',
    description:
      'Students apply the arc length formula s = rθ (with θ in radians) to find arc length, radius, or central angle given the other two quantities. They convert degree measures to radians before applying the formula when necessary.',
    difficulty: 'advanced',
    estimatedMinutes: 25,
    keySkills: [
      'Apply arc length formula s = rθ (θ in radians)',
      'Find arc length, radius, or central angle given two of three',
      'Convert degree measure before applying formula',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-48',
    topicNumber: 198,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.48',
    title: 'Unit Circle: Key Angles and Values',
    description:
      'Students identify the coordinates of key angles (0°, 30°, 45°, 60°, 90°) on the unit circle and read sin and cos directly from those coordinates. They apply unit circle knowledge to evaluate trig expressions without a calculator on the SAT.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Identify coordinates of key angles (0°, 30°, 45°, 60°, 90°)',
      'Read sin and cos from unit circle coordinates',
      'Apply unit circle to evaluate trig expressions without a calculator',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-49',
    topicNumber: 199,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.49',
    title: 'Angle of Elevation and Depression',
    description:
      'Students define the angle of elevation (upward from horizontal) and angle of depression (downward from horizontal), draw and label corresponding diagrams, and apply trigonometry to find heights and distances. They solve realistic SAT word problems involving these angles.',
    difficulty: 'standard',
    estimatedMinutes: 20,
    keySkills: [
      'Define angle of elevation and depression',
      'Draw and label diagrams',
      'Apply trig to find heights and distances',
    ],
    satWeight: '~15% of SAT Math',
  },
  {
    id: 'geo-50',
    topicNumber: 200,
    domain: 'Geometry & Trigonometry',
    skillArea: 'Trigonometry',
    lessonNumber: '4.50',
    title: 'Multi-Step Trigonometry Problem Solving',
    description:
      'Students combine multiple trig relationships, special triangles, and identities to solve complex SAT-style multi-step trigonometry problems. They develop strategic flexibility, choosing the most efficient approach for each problem type.',
    difficulty: 'advanced',
    estimatedMinutes: 30,
    keySkills: [
      'Combine multiple trig relationships in one problem',
      'Apply special triangles and identities strategically',
      'Solve SAT-style multi-step trig problems efficiently',
    ],
    satWeight: '~15% of SAT Math',
  },
]
